CREATE   VIEW [dm_yg1_scm].[VW_DIM_DATE_SCM_SUPPLY_SIMULATION] AS 
 WITH LIST AS (
  SELECT DISTINCT SAP_LOAD_DATE AS SAP_LOAD_DATE
    , CONVERT(date, CAST(SAP_LOAD_DATE AS CHAR(8)), 112)  AS SLICER_DATE
  FROM [dm_yg1_scm].[FACT_SCM_SUPPLY_SIMULATION_PIVOT]
  WHERE SAP_LOAD_DATE >= DATEADD(MONTH, -3, GETDATE())
 ),
 DIM_D AS (
  SELECT DISTINCT SAP_LOAD_DATE
    , TRY_CONVERT(nvarchar, SLICER_DATE) AS SLICER_DATE
  FROM LIST
  UNION ALL
  SELECT MAX(SAP_LOAD_DATE) AS SAP_LOAD_DATE
    , '최신 시행일' AS SLICER_DATE
  FROM LIST
 )
 SELECT *
   , CASE 
   WHEN SLICER_DATE = '최신 시행일' THEN 0
   ELSE DENSE_RANK() OVER (ORDER BY SAP_LOAD_DATE DESC)
    END AS SORT
 FROM DIM_D