CREATE   VIEW [dm_yg1_scm].[VW_FACT_SCM_CAPABALANCE_SIMULATION_LT]
AS
-- 0. 기본 쿼리
WITH BASE AS (
SELECT [CLIENT]
,[SAP_LOAD_DATE]
,A.[WORK_CENTER]
   ,B.WORK_CENTER_NAME
,[MFG_GROUP]
,LT/(B.WORK_CENTER_COUNT*B.CORRECTION_RATE*60*6*120) as LT
,QTY
,[WORK_YEAR]
,[WORK_WEEK]
   ,DATEDIFF(WEEK,DATEFROMPARTS([SAP_LOAD_DATE]/10000,([SAP_LOAD_DATE]/100)%100,[SAP_LOAD_DATE]%100),DATEADD(WEEK,[WORK_WEEK],DATEFROMPARTS(WORK_YEAR,1,1))) as WEEKDIFF
FROM (
 SELECT [CLIENT]
    ,[SAP_LOAD_DATE]
    ,[WORK_CENTER]
    ,[MFG_GROUP]
    ,SUM([OPERATION_HOUR]) as LT
    ,SUM([OPERATION_QTY]) as QTY
    ,[WORK_YEAR]
    ,[WORK_WEEK]
   FROM [dm_yg1_scm].[FACT_SCM_CAPABALANCE_SIMULATION]
   GROUP BY 
     [CLIENT]
    ,[SAP_LOAD_DATE]
    ,[WORK_CENTER]
    ,[MFG_GROUP]
    ,[WORK_YEAR]
    ,[WORK_WEEK]
 UNION ALL
 SELECT B.CLIENT
    ,B.SAP_LOAD_DATE
    ,A.WORK_CENTER
    ,A.MFG_GROUP
    ,NULL   as LT
    ,NULL   as QTY
    ,LEFT(B.SAP_LOAD_DATE, 4) AS WORK_YEAR
    ,DATEPART(WEEK, CAST(CAST(SAP_LOAD_DATE AS CHAR(8)) AS DATE)) AS WORK_WEEK
FROM (SELECT DISTINCT WORK_CENTER, MFG_GROUP FROM [DM_YG1].[dm_yg1_scm].[FACT_SCM_CAPABALANCE_SIMULATION]) A
  CROSS JOIN (SELECT DISTINCT CLIENT, SAP_LOAD_DATE FROM [DM_YG1].[dm_yg1_scm].[FACT_SCM_CAPABALANCE_SIMULATION]) B
    ) A
JOIN dm_yg1_scm.DIM_SCM_WORKCENTER_CAPACITY B
 ON A.WORK_CENTER=B.WORK_CENTER
)
-- 1. 원본 쿼리
SELECT [CLIENT]
,[SAP_LOAD_DATE]
,[WORK_CENTER]
   ,[WORK_CENTER_NAME]
,[MFG_GROUP]
,[LT]
,[QTY]
,[WORK_YEAR]
,[WORK_WEEK]
FROM BASE
WHERE WEEKDIFF >= 0
UNION ALL
-- 2. MFG_GROUP 기준 그룹화
SELECT 
[CLIENT]
,[SAP_LOAD_DATE]
,'최대' AS [WORK_CENTER]
,'ㅤㅤㅤㅤ' AS [WORK_CENTER_NAME]
,[MFG_GROUP]
,MAX(LT) AS LT
,MAX(QTY) AS QTY
,[WORK_YEAR]
,[WORK_WEEK]
FROM BASE A
WHERE WEEKDIFF >= 0
GROUP BY 
[CLIENT]
,[SAP_LOAD_DATE]
,[MFG_GROUP]
,[WORK_YEAR]
,[WORK_WEEK]
UNION ALL
-- 3. WORK_CENTER 기준 그룹화
SELECT 
[CLIENT]
,[SAP_LOAD_DATE]
,[WORK_CENTER]
,[WORK_CENTER_NAME]
,'최대' AS [MFG_GROUP]
,MAX(LT) AS LT
,MAX(QTY) AS QTY
,[WORK_YEAR]
,[WORK_WEEK]
FROM BASE A
WHERE WEEKDIFF >= 0
GROUP BY 
[CLIENT]
,[SAP_LOAD_DATE]
,[WORK_CENTER]
,[WORK_CENTER_NAME]
,[WORK_YEAR]
,[WORK_WEEK]