CREATE VIEW [dm_yg1_scm].[VW_FACT_SCM_SUPPLY_SIMULATION_TB_REPORT]
AS
SELECT A.[CLIENT]
,A.[SAP_LOAD_DATE]
,A.[PO]
,[MATERIAL]
,A.[BOM_MATERIAL]
,[CURRENT_TEXT_KEY]
   ,1000 as [PLANT_KEY]
   ,'서운공장' as PLANT_NAME
,[KTEXT]
,[GROUP]
,[CURRENT_WORK_INPUT_DATE]
,[OPER_INPUT_YN]
,[QTY]
,[REQMTS_QTY]
   ,REMAINED_LT
,[MTART]
,[BOM_TYPE]
,[MATKL]
,[BOM_INPUT_YN]
   ,PLAN_DATE AS PLAN_DATE
,[RDD]
,[RDD_6W]
,[RDD_WEEK]
,[OPERATION_KEY]
,[SYSTEM_STATUS]
,[BATCH]
,[INV_QTY]
,[FROM_SLOC]
,[TO_SLOC],
    [INVEN_STATUS],
[T0_KTSCH] [절단] ,
  [T1_KTSCH] [포인트연삭] ,
  [T2_KTSCH] [센터연삭] ,
  [T3_KTSCH] [센터랩핑] ,
  [T4_KTSCH] [센터레스] ,
  [T5_KTSCH] [백테이퍼] ,
  [T6_KTSCH] [볼황삭] ,
  [T7_KTSCH] [원통] ,
  [T8_KTSCH] [INFEED] ,
  [T9_KTSCH] [홈연삭] ,
  [T10_KTSCH] [TANG] ,
  [T11_KTSCH] [원척킹] ,
  [T12_KTSCH] [밑날연삭] ,
  [T13_KTSCH] "호닝[MANUAL]" ,
  [T14_KTSCH] [TOYO폴리싱] ,
  [T15_KTSCH] [평면연삭] ,
  [T16_KTSCH] [슬롯연삭] ,
  [T17_KTSCH] [NECK] ,
  [T18_KTSCH] [여유면연삭] ,
  [T19_KTSCH] "호닝[Cleaning]" ,
  [T20_KTSCH] [세척] ,
  [T0_WORK_DATE] [절단_DATE] ,
  [T1_WORK_DATE] [포인트연삭_DATE] ,
  [T2_WORK_DATE] [센터연삭_DATE] ,
  [T3_WORK_DATE] [센터랩핑_DATE] ,
  [T4_WORK_DATE] [센터레스_DATE] ,
  [T5_WORK_DATE] [백테이퍼_DATE] ,
  [T6_WORK_DATE] [볼황삭_DATE] ,
  [T7_WORK_DATE] [원통_DATE] ,
  [T8_WORK_DATE] [INFEED_DATE] ,
  [T9_WORK_DATE] [홈연삭_DATE] ,
  [T10_WORK_DATE] [TANG_DATE] ,
  [T11_WORK_DATE] [원척킹_DATE] ,
  [T12_WORK_DATE] [밑날연삭_DATE] ,
  [T13_WORK_DATE] "호닝[MANUAL]_DATE" ,
  [T14_WORK_DATE] [TOYO폴리싱_DATE] ,
  [T15_WORK_DATE] [평면연삭_DATE] ,
  [T16_WORK_DATE] [슬롯연삭_DATE] ,
  [T17_WORK_DATE] [NECK_DATE] ,
  [T18_WORK_DATE] [여유면연삭_DATE] ,
  [T19_WORK_DATE] "호닝[Cleaning]_DATE" ,
  [T20_WORK_DATE] [세척_DATE] 
FROM [dm_yg1_scm].[FACT_SCM_SUPPLY_SIMULATION_TB_REPORT] A
LEFT OUTER JOIN dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_INVEN_STATUS B
ON A.CLIENT=B.CLIENT AND A.SAP_LOAD_DATE=B.SAP_LOAD_DATE AND A.BOM_MATERIAL=B.BOM_MATERIAL
LEFT OUTER JOIN dm_yg1_scm.DIM_SCM_AUFNR_PLAN_DATE C
ON A.CLIENT=C.MANDT AND A.PO=C.AUFNR AND A.SAP_LOAD_DATE/100=C.ERSDA/100
LEFT OUTER JOIN (
SELECT *
FROM [dm_yg1_scm].[FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING]
WHERE STATUS='현공정'
) D
ON A.CLIENT=D.CLIENT AND A.SAP_LOAD_DATE=D.SAP_LOAD_DATE 
AND A.PO=D.PO