CREATE VIEW  [dm_yg1_scm].[VW_FACT_SCM_SUPPLY_SIMULATION_PIVOT] AS 
/****************************************************************************************************************
SP 명  : VW_FACT_SCM_SUPPLY_SIMULATION_PIVOT
SP 제목  : SCM 공급 시뮬레이션 - PIVOT VIEW 
최초작성자 : 김기만
최초작성일 : 2024.11.12
SP 실행 예 : SELECT * FROM DM_YG1.dm_yg1_scm.VW_FACT_SCM_SUPPLY_SIMULATION_PIVOT 
SP 설명  : SCM 공급 시뮬레이션 - PIVOT VIEW 
   
변경이력  : 변경일/변경자/요청자/요청일/내용 
     
******************************************************************************************************************/
SELECT T.[CLIENT]
,T.[SAP_LOAD_DATE]
,T.[PO]
,[MATERIAL]
,T.[BOM_MATERIAL]
,[CURRENT_TEXT_KEY]
,[KTEXT]
,[GROUP]
,[CURRENT_WORK_INPUT_DATE]
,[OPER_INPUT_YN]
,[QTY]
,[REQMTS_QTY]
,[MTART]
,[BOM_TYPE]
,[MATKL]
,[BOM_INPUT_YN]
,[RDD]
,[RDD_6주] AS RDD_6W
,[RDD_WEEK]
,[OPERATION_KEY]
,[SYSTEM_STATUS]
,[INV_QTY]
   ,ISNULL(A1.REMAINED_LT, A6.REMAINED_LT) AS REMAINED_LT
   ,B.INVEN_STATUS
   ,C.PLAN_DATE
,[WORKNAME01] AS 'Process-1'
   ,A1.WORK_PROCESS AS 'Status-1'
,[WORKNAME02] AS 'Process-2'
   ,A2.WORK_PROCESS AS 'Status-2'
,[WORKNAME03] AS 'Process-3'
   ,A3.WORK_PROCESS AS 'Status-3'
   ,[WORKNAME04] AS 'Process-4'
   ,A4.WORK_PROCESS AS 'Status-4'
,[WORKNAME05] AS 'Process-5'
   ,A5.WORK_PROCESS AS 'Status-5'
,[WORKNAME06] AS 'Process-6'
   ,A6.WORK_PROCESS AS 'Status-6'
,[WORKNAME07] AS 'Process-7'
   ,A7.WORK_PROCESS AS 'Status-7'
,[WORKNAME08] AS 'Process-8'
   ,A8.WORK_PROCESS AS 'Status-8'
,[WORKNAME09] AS 'Process-9'
   ,A9.WORK_PROCESS AS 'Status-9'
   ,[WORKNAME10] AS 'Process-10'
   ,A10.WORK_PROCESS AS 'Status-10'
,[WORKNAME11] AS 'Process-11'
   ,A11.WORK_PROCESS AS 'Status-11'
,[WORKNAME12] AS 'Process-12'
   ,A12.WORK_PROCESS AS 'Status-12'
   ,[WORKNAME13] AS 'Process-13'
   ,A13.WORK_PROCESS AS 'Status-13'
,[WORKNAME14] AS 'Process-14'
   ,A14.WORK_PROCESS AS 'Status-14'
,[WORKNAME15] AS 'Process-15'
   ,A15.WORK_PROCESS AS 'Status-15'
   ,T.ETL_DATE
   
FROM [dm_yg1_scm].[FACT_SCM_SUPPLY_SIMULATION_PIVOT] T
LEFT JOIN DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A1  ON T.CLIENT = A1.CLIENT   AND T.SAP_LOAD_DATE = A1.SAP_LOAD_DATE  AND T.PO = A1.PO  AND T.VORNR1  = A1.WORK_STATUS
LEFT JOIN DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A2  ON T.CLIENT = A2.CLIENT   AND T.SAP_LOAD_DATE = A2.SAP_LOAD_DATE  AND T.PO = A2.PO  AND T.VORNR2  = A2.WORK_STATUS
LEFT JOIN DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A3  ON T.CLIENT = A3.CLIENT   AND T.SAP_LOAD_DATE = A3.SAP_LOAD_DATE  AND T.PO = A3.PO  AND T.VORNR3  = A3.WORK_STATUS
LEFT JOIN DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A4  ON T.CLIENT = A4.CLIENT   AND T.SAP_LOAD_DATE = A4.SAP_LOAD_DATE  AND T.PO = A4.PO  AND T.VORNR4  = A4.WORK_STATUS
LEFT JOIN DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A5  ON T.CLIENT = A5.CLIENT   AND T.SAP_LOAD_DATE = A5.SAP_LOAD_DATE  AND T.PO = A5.PO  AND T.VORNR5  = A5.WORK_STATUS
LEFT JOIN DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A6  ON T.CLIENT = A6.CLIENT   AND T.SAP_LOAD_DATE = A6.SAP_LOAD_DATE  AND T.PO = A6.PO  AND T.VORNR6  = A6.WORK_STATUS
LEFT JOIN DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A7  ON T.CLIENT = A7.CLIENT   AND T.SAP_LOAD_DATE = A7.SAP_LOAD_DATE  AND T.PO = A7.PO  AND T.VORNR7  = A7.WORK_STATUS
LEFT JOIN DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A8  ON T.CLIENT = A8.CLIENT   AND T.SAP_LOAD_DATE = A8.SAP_LOAD_DATE  AND T.PO = A8.PO  AND T.VORNR8  = A8.WORK_STATUS
LEFT JOIN DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A9  ON T.CLIENT = A9.CLIENT   AND T.SAP_LOAD_DATE = A9.SAP_LOAD_DATE  AND T.PO = A9.PO  AND T.VORNR9  = A9.WORK_STATUS
LEFT JOIN DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A10 ON T.CLIENT = A10.CLIENT  AND T.SAP_LOAD_DATE = A10.SAP_LOAD_DATE AND T.PO = A10.PO AND T.VORNR10 = A10.WORK_STATUS
LEFT JOIN DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A11 ON T.CLIENT = A11.CLIENT  AND T.SAP_LOAD_DATE = A11.SAP_LOAD_DATE AND T.PO = A11.PO AND T.VORNR11 = A11.WORK_STATUS
LEFT JOIN DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A12 ON T.CLIENT = A12.CLIENT  AND T.SAP_LOAD_DATE = A12.SAP_LOAD_DATE AND T.PO = A12.PO AND T.VORNR12 = A12.WORK_STATUS
LEFT JOIN DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A13 ON T.CLIENT = A13.CLIENT  AND T.SAP_LOAD_DATE = A13.SAP_LOAD_DATE AND T.PO = A13.PO AND T.VORNR13 = A13.WORK_STATUS
LEFT JOIN DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A14 ON T.CLIENT = A14.CLIENT  AND T.SAP_LOAD_DATE = A14.SAP_LOAD_DATE AND T.PO = A14.PO AND T.VORNR14 = A14.WORK_STATUS
LEFT JOIN DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A15 ON T.CLIENT = A15.CLIENT  AND T.SAP_LOAD_DATE = A15.SAP_LOAD_DATE AND T.PO = A15.PO AND T.VORNR15 = A15.WORK_STATUS
LEFT JOIN dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_INVEN_STATUS B ON T.CLIENT = B.CLIENT   AND T.SAP_LOAD_DATE = B.SAP_LOAD_DATE   AND T.BOM_MATERIAL = B.BOM_MATERIAL
LEFT JOIN dm_yg1_scm.DIM_SCM_AUFNR_PLAN_DATE      C ON T.CLIENT = C.MANDT   AND T.SAP_LOAD_DATE/100 = C.ERSDA/100   AND T.PO = C.AUFNR
WHERE CONVERT(date, CAST(T.SAP_LOAD_DATE AS CHAR(8)), 112) >= DATEADD(MONTH, -3, GETDATE())