CREATE       VIEW [dm_yg1_scm].[VW_DIM_DATE_SCM_CAPA_BALANCE] AS 
WITH LIST AS (
 SELECT DISTINCT SAP_LOAD_DATE AS SAP_LOAD_DATE
   , CAST(SAP_LOAD_DATE AS CHAR(8))  AS SLICER_DATE
   , WORK_YEAR
   , WORK_WEEK
   , CASE 
    WHEN WORK_YEAR  <= LEFT([SAP_LOAD_DATE], 4) 
    THEN FORMAT(WORK_WEEK,'0#') 
    ELSE 'Y' + RIGHT(WORK_YEAR, 2) + '-' + FORMAT(WORK_WEEK,'0#') --
   END AS SLICER_WEEK
 FROM [dm_yg1_scm].[FACT_SCM_CAPABALANCE_ORDER_N]
WHERE (WORK_YEAR > YEAR(CONVERT(date, CAST(SAP_LOAD_DATE AS CHAR(8)), 112))
   OR (WORK_YEAR = YEAR(CONVERT(date, CAST(SAP_LOAD_DATE AS CHAR(8)), 112)) AND WORK_WEEK >= DATEPART(WEEK, CONVERT(date, CAST(SAP_LOAD_DATE AS CHAR(8)), 112))))
  AND CONVERT(date, CAST(SAP_LOAD_DATE AS CHAR(8)), 112) >= DATEADD(MONTH, -3, GETDATE())
),
DIM_D AS (
SELECT SAP_LOAD_DATE
  , '최신 시행일'   AS SLICER_DATE
  , WORK_YEAR
  , WORK_WEEK
  , '해당 주차'   AS SLICER_WEEK
FROM LIST
WHERE SAP_LOAD_DATE = (SELECT MAX(SAP_LOAD_DATE) FROM [dm_yg1_scm].[FACT_SCM_CAPABALANCE_ORDER])
AND WORK_YEAR = YEAR(SLICER_DATE)
AND WORK_WEEK = DATEPART(WEEK, SLICER_DATE)
  UNION ALL
  
SELECT SAP_LOAD_DATE
  , '최신 시행일'   AS SLICER_DATE
  , WORK_YEAR
  , WORK_WEEK
  , SLICER_WEEK
FROM LIST
WHERE SAP_LOAD_DATE = (SELECT MAX(SAP_LOAD_DATE) FROM [dm_yg1_scm].[FACT_SCM_CAPABALANCE_ORDER])
  UNION ALL
  
SELECT SAP_LOAD_DATE
  , SLICER_DATE
  , WORK_YEAR
  , WORK_WEEK
  , '해당 주차'   AS SLICER_WEEK
FROM LIST
WHERE WORK_WEEK = DATEPART(WEEK, SLICER_DATE) 
  UNION ALL
SELECT SAP_LOAD_DATE
  , SLICER_DATE
  , WORK_YEAR
  , WORK_WEEK
  , SLICER_WEEK 
FROM LIST
)
SELECT *
  , CASE 
   WHEN SLICER_DATE = '최신 시행일' THEN 0
   ELSE DENSE_RANK() OVER (ORDER BY SAP_LOAD_DATE DESC)
    END AS DATE_SORT
  , CASE
   WHEN SLICER_WEEK =  '해당 주차' THEN 0
   WHEN SLICER_WEEK LIKE 'Y%'    THEN WORK_YEAR * 100 + RIGHT(WORK_WEEK, 1)
   ELSE SLICER_WEEK
    END AS WEEK_SORT
FROM DIM_D