CREATE VIEW scm.VW_CAPA_MTRL_GROUP
AS
SELECT 'EM-CBN' [Material group], 'CAR' [mtrl type] UNION ALL
SELECT 'EM-CBR', 'CAR' UNION ALL
SELECT 'EM-CRG', 'CAR' UNION ALL
SELECT 'EM-CSQ', 'CAR' UNION ALL
SELECT 'EM-HBR', 'HSS' UNION ALL
SELECT 'EM-HCB', 'HSS' UNION ALL
SELECT 'EM-HCR', 'CAR' UNION ALL
SELECT 'EM-HRG', 'HSS' UNION ALL
SELECT 'EM-HSQ', 'HSS' UNION ALL
SELECT 'EM-PCD', 'CAR' UNION ALL
SELECT 'EM-SEMI', 'CAR' 