CREATE VIEW [scm].[VM_PSI_PROJECTION_ITEM_LIST]
AS
SELECT PRDHA Material_HIERARCHY,
A.MATNR AS EDP,
D.VTEXT AS BRAND
FROM DW_YG1.dbo.TB_DW_DIM_MARA A
JOIN DW_YG1.dbo.TB_DW_DIM_T179T D
ON a.PRDHA=D.PRODH