CREATE VIEW [scm].[VW_PSI_PROJECTION_DIM]
AS
SELECT
A.MANDT,
A.MATNR MATERIAL,
A.GRDP_005 EDP,
B.MAKTG AS BRAND,
A.PRDHA AS PRODUCT_HIERARCY,
TRIM(A.FERTH) AS UNCOATING,
C.HERKL ,
CASE WHEN DISPO LIKE 'CO%' THEN A.KOSCH
ELSE NULL END AS MEMO,
MTART AS MATERIAL_TYPE,
SPART AS DIVISION,
MATKL AS MATERIAL_GROUP,
GROES AS SIZE_DIMENSION,
EXTWG AS EXT_MATERIAL_GROUP,
GRDP_PSS AS PSS,
GRDP_PLC AS PLC
FROM DW_YG1.DBO.TB_DW_DIM_MARA A
JOIN DW_YG1.DBO.TB_DW_DIM_MAKT B
ON A.MATNR_KEY=B.MATNR_KEY AND A.MANDT=B.MANDT
JOIN DW_YG1.DBO.TB_DW_DIM_MARC C
ON A.MATNR_KEY=C.MATNR_KEY  AND A.MANDT=C.MANDT AND C.WERKS=1000