-- https://school.programmers.co.kr/learn/courses/30/lessons/131534

-- 코드를 입력하세요


SELECT YEAR(SALES_DATE) YEAR, 
       MONTH(SALES_DATE) MONTH,
       COUNT(DISTINCT O.USER_ID),
       ROUND(COUNT(DISTINCT O.USER_ID)/(SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO
       WHERE YEAR(JOINED)=2021),1)
FROM ONLINE_SALE O
LEFT OUTER JOIN
(SELECT USER_ID,JOINED
FROM USER_INFO) U
ON O.USER_ID=U.USER_ID
WHERE YEAR(U.JOINED)=2021

GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH