USE [DM_YG1]
GO

/****** Object:  StoredProcedure [dm_yg1_scm].[PROC_FACT_SCM_CAPABALANCE_ORDER]    Script Date: 2025-07-25 오후 12:35:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






/****************************************************************************************************************
SP 명		: PROC_FACT_SCM_CAPABALANCE_ORDER
SP 제목		: CAPABALANCE Table Insert
최초작성자	: 최은수
최초작성일	: 2024.12.22

	
******************************************************************************************************************/

CREATE   PROCEDURE [dm_yg1_scm].[PROC_FACT_SCM_CAPABALANCE_ORDER]
AS
BEGIN

	
	--공통변수
	DECLARE @SP_START_EXEC		DATETIME = GETDATE()	-- SP 실행시작시간
	DECLARE @INSERT_CNT	INT = 0			-- INSERT 건수
	DECLARE @UPDATE_CNT	INT = 0			-- UPDATE 건수
	DECLARE @DELETE_CNT	INT = 0			-- DELETE 건수
	DECLARE	@TABLE_NM	VARCHAR(50) = 'FACT_SCM_CAPABALANCE_ORDER'	-- TARGET TABLE NAME
	DECLARE @ERR_MSG	VARCHAR(4000)
	DECLARE @ERR_NUM	NVARCHAR(20)
	DECLARE @ERR_LINE	INT
	DECLARE @ERSDA INT =(SELECT MAX(ERSDA) FROM  DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB)
	
	
	DECLARE @COMPANY_CD	VARCHAR(12)	= '1000'	-- 회사코드 (SAP 필드명 : BUKRS) 

	BEGIN TRY

	DELETE FROM DM_YG1.dm_yg1_scm.[FACT_SCM_CAPABALANCE_ORDER]
	WHERE [SAP_LOAD_DATE]=@ERSDA
	SET @DELETE_CNT=@@ROWCOUNT


	INSERT INTO [dm_yg1_scm].[FACT_SCM_CAPABALANCE_ORDER]
           ([CLIENT]
           ,[SAP_LOAD_DATE]
           ,[PO]
           ,[KTSCH]
           ,[WORK_CENTER]
           ,[VORNR]
           ,[APLZL]
           ,[MFG_GROUP]
           ,[MATNR]
           ,[LT]
           ,[LTXA1]
           ,[OPERATION_QTY]
           ,[WORK_YEAR]
           ,[WORK_WEEK]
           ,[ERDAT]
           ,[RDD]
           ,[ETL_TIME]
		   ,[MATKL])
		   

SELECT 
A.MANDT
,A.ERSDA
,A.AUFNR
,A.KTSCH
,C.ARBPL
,VORNR
,A.APLZL
,ISNULL(E.MFG,'기타') as MFG
,D.MATNR
,A.GAMNG*VGW02+VGW01 as LT
,LTXA1
,A.GAMNG
,DATEPART(year,DATEADD(WEEK,6,DATEFROMPARTS(D.ERDAT/10000,(D.ERDAT/100%100),D.ERDAT%100))) AS RDDYEAR
,DATEPART(WEEK,DATEADD(WEEK,6,DATEFROMPARTS(D.ERDAT/10000,(D.ERDAT/100%100),D.ERDAT%100))) AS RDDWEEK
,DATEFROMPARTS(D.ERDAT/10000,(D.ERDAT/100%100),D.ERDAT%100) ERDAT
,DATEADD(WEEK,6,DATEFROMPARTS(D.ERDAT/10000,(D.ERDAT/100%100),D.ERDAT%100)) as RDD
,@SP_START_EXEC
,a.MATKL 
FROM (SELECT A.*,B.KTSCH,B.VORNR,C.APLZL,B.VGW01,B.VGW02,B.LTXA1,ARBID
FROM DW_YG1.SCM.TB_DW_DIM_ZDWT005_COOIS A  WITH(NOLOCK)
JOIN DW_YG1.scm.TB_SCM_ZROUTING B WITH(NOLOCK)
ON A.PLNNR=B.PLNNR AND A.PLNAL=B.PLNAL
JOIN DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB C WITH(NOLOCK)
ON A.AUFNR=C.AUFNR AND A.AUFPL=C.AUFPL AND A.ERSDA=C.ERSDA AND B.OBJID=C.ARBID
WHERE A.ERSDA =@ERSDA
	) A
JOIN(

SELECT *
FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A WITH(NOLOCK)
WHERE WORK_PROCESS='현공정' OR WORK_PROCESS='이후 공정'

) B
ON A.AUFNR=B.PO AND A.APLZL=B.APLZL AND A.ERSDA=B.SAP_LOAD_DATE AND A.AUFPL=B.AUFPL
JOIN DW_YG1.scm.TB_DW_DIM_CRHD C WITH(NOLOCK)
ON A.ARBID=C.[OBJID]
LEFT OUTER JOIN DW_YG1.scm.TB_DW_DIM_ZDWT005_COOIS D WITH(NOLOCK)
ON A.MANDT=D.MANDT AND A.ERSDA=D.ERSDA AND A.AUFNR=D.AUFNR
LEFT OUTER JOIN (
SELECT DISTINCT  MATNR,MIN(MFG) MFG
from DW_YG1.scm.TB_SCM_MFG_TABLE WITH(NOLOCK)
GROUP BY MATNR
) E
ON D.MATNR=E.MATNR

		SET @INSERT_CNT	= @@ROWCOUNT

		INSERT INTO DW_YG1.DBO.TB_ETL_LOG
					(DB_NM			, SP_NM							, TABLE_NM		, START_DATE		, END_DATE		
					, INSERT_CNT	, DELETE_CNT	, UPDATE_CNT	, SUCCEESS_YN	, ERR_MSG			, ERR_NUM	, ERR_LINE)
			VALUES	(DB_NAME()		, OBJECT_NAME(@@PROCID)			, @TABLE_NM		, @SP_START_EXEC	, GETDATE()
					, @INSERT_CNT	, @DELETE_CNT	, @UPDATE_CNT	, 'Y'			, NULL				, NULL		, NULL)
			
	END TRY

	BEGIN CATCH
			
		SET @ERR_MSG	= ERROR_MESSAGE()
		SET @ERR_NUM	= ERROR_NUMBER()
		SET @ERR_LINE	= ERROR_LINE()

		PRINT	@ERR_MSG
		
		INSERT INTO DW_YG1.DBO.TB_ETL_LOG
				(DB_NM			, SP_NM							, TABLE_NM		, START_DATE		, END_DATE		
				, INSERT_CNT	, DELETE_CNT	, UPDATE_CNT	, SUCCEESS_YN	, ERR_MSG			, ERR_NUM		, ERR_LINE)
		VALUES	(DB_NAME()		, OBJECT_NAME(@@PROCID)			, @TABLE_NM		, @SP_START_EXEC	, GETDATE()
				, @INSERT_CNT	, @DELETE_CNT	, @UPDATE_CNT	, 'N'			, ERROR_MESSAGE()	, ERROR_NUMBER(), ERROR_LINE());
	END CATCH
END

GO


