/****************************************************************************************************************
SP 명  : PROC_TB_SCM_10_STO_INS
SP Owner    : scm
SP 제목  : INPUT 
최초작성자 : 최은수
최초작성일 : 2024.09.11
SP 실행 예 : EXEC scm.PROC_TB_SCM_10_STO_INS
SP 설명  : STO 입력
변경이력  : 변경일/변경자/요청자/요청일/내용 
******************************************************************************************************************/
CREATE PROCEDURE [scm].[PROC_TB_SCM_DATA_INS_MAIN]
AS
BEGIN
DECLARE 
  @INSERT_CNT INT = 0,  -- INSERT 건수
  @UPDATE_CNT INT = 0,  -- UPDATE 건수
  @DELETE_CNT INT = 0,  -- DELETE 건수
  @TABLE_NM VARCHAR(50) = 'SCM_DATA_INS_MAIN',   -- TARGET TABLE NAME
  @SP_START_EXEC DATETIME = GETDATE()             -- SP 실행시작시간
 BEGIN TRY
 --EXEC [scm].[PROC_TB_SCM_0_PLAN_INS] @SP_START_EXEC
 --EXEC [scm].[PROC_TB_SCM_1_COATING_ORDER_INS] @SP_START_EXEC
 --EXEC [scm].[PROC_TB_SCM_1_NONCOATING_ORDER_INS]  @SP_START_EXEC
 --EXEC [scm].[PROC_TB_SCM_2_ORDER_STATUS_INS] @SP_START_EXEC
 --EXEC [scm].[PROC_TB_SCM_3_ORDER_ROUTING_INS] @SP_START_EXEC
 --EXEC [scm].[PROC_TB_SCM_4_SO_INS] @SP_START_EXEC
 --EXEC [scm].[PROC_TB_SCM_5_TR_INS] @SP_START_EXEC
 --EXEC [scm].[PROC_TB_SCM_6_INVEN_CAPA_INS] @SP_START_EXEC
 --EXEC [scm].[PROC_TB_SCM_6_INVEN_PSI_INS] @SP_START_EXEC
 
 --EXEC [scm].[PROC_TB_SCM_8_PURCHASE_PO_INS] @SP_START_EXEC
 --EXEC [scm].[PROC_TB_SCM_9_PRE_PROC_INS] @SP_START_EXEC
 
 EXEC [scm].[PROC_TB_DW_DIM_ZDWT005_COOIS] @SP_START_EXEC
 EXEC [scm].[PROC_TB_DW_FACT_ZDWT006_Z25PP031] @SP_START_EXEC
 EXEC [scm].[PROC_TB_DW_FACT_ZDWT007_Z25MM034] @SP_START_EXEC
 EXEC [scm].[PROC_TB_DW_FACT_ZDWT008_Z25MM012] @SP_START_EXEC
 EXEC [scm].[PROC_TB_DW_FACT_ZDWT009_Z25MM001] @SP_START_EXEC
 EXEC [scm].[PROC_TB_DW_FACT_ZDWT010_Z25SD003] @SP_START_EXEC
 EXEC [scm].[PROC_TB_DW_FACT_ZDWT011_Z25PP016] @SP_START_EXEC
 EXEC [scm].[PROC_TB_DW_FACT_ZDWT005_ROUTING_TB] @SP_START_EXEC
 EXEC [scm].[PROC_TB_DW_FACT_ZDWT016_Z25MM034] @SP_START_EXEC
 EXEC [scm].[PROC_TB_DW_FACT_SCM_SUPPLY_SIMULATION_RESULT]
  INSERT INTO DW_YG1.DBO.TB_ETL_LOG
     (DB_NM   , SP_NM       , TABLE_NM  , START_DATE  , END_DATE  
     , INSERT_CNT , DELETE_CNT , UPDATE_CNT , SUCCEESS_YN , ERR_MSG   , ERR_NUM , ERR_LINE)
   VALUES (DB_NAME()  , OBJECT_NAME(@@PROCID)   , @TABLE_NM  , @SP_START_EXEC , GETDATE()
     , @INSERT_CNT , @DELETE_CNT , @UPDATE_CNT , 'Y'   , NULL    , NULL  , NULL)
 END TRY
 BEGIN CATCH
  INSERT INTO DW_YG1.DBO.TB_ETL_LOG
     (DB_NM   , SP_NM       , TABLE_NM  , START_DATE  , END_DATE  
     , INSERT_CNT , DELETE_CNT , UPDATE_CNT , SUCCEESS_YN , ERR_MSG   , ERR_NUM  , ERR_LINE)
   VALUES (DB_NAME()  , OBJECT_NAME(@@PROCID)   , @TABLE_NM  , @SP_START_EXEC , GETDATE()
     , @INSERT_CNT , @DELETE_CNT , @UPDATE_CNT , 'N'   , ERROR_MESSAGE() , ERROR_NUMBER(), ERROR_LINE())
  
  RETURN
 END CATCH
END