/****************************************************************************************************************
SP 명  : PROC_TB_DW_FACT_ZDWT009_Z25MM001
SP Owner    : scm
SP 제목  : INPUT 
최초작성자 : 최은수
최초작성일 : 2024.09.11
SP 실행 예 : EXEC scm.PROC_TB_DW_FACT_ZDWT009_Z25MM001
SP 설명  : PLAN 입력
변경이력  : 변경일/변경자/요청자/요청일/내용 
******************************************************************************************************************/
CREATE PROCEDURE [scm].[PROC_TB_DW_FACT_ZDWT013_Z25MM001]
 @CUR_DATE DATE
AS
BEGIN
DECLARE 
  @INSERT_CNT INT = 0,  -- INSERT 건수
  @UPDATE_CNT INT = 0,  -- UPDATE 건수
  @DELETE_CNT INT = 0,  -- DELETE 건수
  @TABLE_NM VARCHAR(50) = 'TB_DW_FACT_ZDWT013_Z25MM001',   -- TARGET TABLE NAME
  @SP_START_EXEC DATETIME = GETDATE()             -- SP 실행시작시간
 BEGIN TRY
DELETE FROM scm.TB_DW_FACT_ZDWT013_Z25MM001
WHERE ERSDA IN (
SELECT DISTINCT ERSDA
FROM ODS_YG1.ods_scm.TB_ODS_ZDWT013_Z25MM001_CHANGE
)
SET @DELETE_CNT=@@ROWCOUNT
INSERT INTO DW_YG1.scm.TB_DW_FACT_ZDWT013_Z25MM001
SELECT *
  ,@CUR_DATE AS LOAD_DT
FROM ODS_YG1.ods_scm.TB_ODS_ZDWT013_Z25MM001_CHANGE
WHERE WERKS=1000
SET @INSERT_CNT=@@ROWCOUNT
  
  INSERT INTO DW_YG1.DBO.TB_ETL_LOG
     (DB_NM   , SP_NM       , TABLE_NM  , START_DATE  , END_DATE  
     , INSERT_CNT , DELETE_CNT , UPDATE_CNT , SUCCEESS_YN , ERR_MSG   , ERR_NUM , ERR_LINE)
   VALUES (DB_NAME()  , OBJECT_NAME(@@PROCID)   , @TABLE_NM  , @SP_START_EXEC , GETDATE()
     , @INSERT_CNT , @DELETE_CNT , @UPDATE_CNT , 'Y'   , NULL    , NULL  , NULL)
 END TRY
 BEGIN CATCH
  INSERT INTO DW_YG1.DBO.TB_ETL_LOG
     (DB_NM   , SP_NM       , TABLE_NM  , START_DATE  , END_DATE  
     , INSERT_CNT , DELETE_CNT , UPDATE_CNT , SUCCEESS_YN , ERR_MSG   , ERR_NUM  , ERR_LINE)
   VALUES (DB_NAME()  , OBJECT_NAME(@@PROCID)   , @TABLE_NM  , @SP_START_EXEC , GETDATE()
     , @INSERT_CNT , @DELETE_CNT , @UPDATE_CNT , 'N'   , ERROR_MESSAGE() , ERROR_NUMBER(), ERROR_LINE())
  
  RETURN
 END CATCH
END