COLUMN: CLIENT int NOT NULL
COLUMN: SAP_LOAD_DATE int NOT NULL
COLUMN: STAT_TYPE varchar(30) NOT NULL
COLUMN: X_VARIABLE varchar(30) NOT NULL
COLUMN: Y_VARIABLE varchar(30) NOT NULL
COLUMN: TARGET_VALUE numeric NULL
COLUMN: ETL_TIME date NOT NULL