COLUMN: CLIENT int NOT NULL
COLUMN: SAP_LOAD_DATE nvarchar(16) NOT NULL
COLUMN: PO bigint NOT NULL
COLUMN: MATERIAL nvarchar(60) NULL
COLUMN: BOM_MATERIAL nvarchar(60) NULL
COLUMN: CURRENT_TEXT_KEY nvarchar(14) NULL
COLUMN: KTEXT nvarchar(40) NULL
COLUMN: GROUP varchar(17) NULL
COLUMN: CURRENT_WORK_INPUT_DATE nvarchar(20) NULL
COLUMN: OPER_INPUT_YN varchar(6) NOT NULL
COLUMN: QTY numeric NULL
COLUMN: REQMTS_QTY numeric NULL
COLUMN: MTART nvarchar(8) NULL
COLUMN: BOM_TYPE varchar(6) NOT NULL
COLUMN: MATKL nvarchar(54) NULL
COLUMN: BOM_INPUT_YN varchar(10) NULL
COLUMN: RDD varchar(30) NULL
COLUMN: RDD_6W date NULL
COLUMN: RDD_WEEK int NULL
COLUMN: OPERATION_KEY varchar(61) NULL
COLUMN: SYSTEM_STATUS nvarchar(60) NULL
COLUMN: BATCH nvarchar(60) NULL
COLUMN: INV_QTY numeric NULL
COLUMN: FROM_SLOC int NULL
COLUMN: TO_SLOC int NULL
COLUMN: ETL_DATE datetime NULL