COLUMN: CLIENT int NOT NULL
COLUMN: SAP_LOAD_DATE nvarchar(8000) NULL
COLUMN: ERSDA date NULL
COLUMN: MATNR varchar(30) NOT NULL
COLUMN: REGION varchar(4) NULL
COLUMN: PRJTYPE varchar(4) NOT NULL
COLUMN: VAL decimal NULL
COLUMN: ETL_DATE datetime NOT NULL