COLUMN: CLIENT int NOT NULL
COLUMN: SAP_LOAD_DATE int NOT NULL
COLUMN: DIM varchar(30) NOT NULL
COLUMN: STDDEV numeric NULL
COLUMN: EXPECTATION numeric NULL
COLUMN: MAXIMUM numeric NULL
COLUMN: MINIMUN numeric NULL
COLUMN: ETL_TIME datetime NULL