COLUMN: CLIENT int NOT NULL
COLUMN: SAP_LOAD_DATE int NOT NULL
COLUMN: PO int NOT NULL
COLUMN: KTSCH varchar(10) NULL
COLUMN: WORK_CENTER varchar(10) NOT NULL
COLUMN: VORNR int NULL
COLUMN: APLZL int NULL
COLUMN: MFG_GROUP varchar(20) NOT NULL
COLUMN: MATNR nvarchar(60) NULL
COLUMN: LT numeric NOT NULL
COLUMN: LTXA1 nvarchar(100) NOT NULL
COLUMN: OPERATION_QTY int NOT NULL
COLUMN: WORK_YEAR int NOT NULL
COLUMN: WORK_WEEK int NOT NULL
COLUMN: ERDAT date NULL
COLUMN: RDD date NULL
COLUMN: ETL_TIME datetime NOT NULL
COLUMN: MATKL varchar(30) NULL