CREATE VIEW [dm_yg1_scm].VW_FACT_SCM_CAPABALANCE_SIMULATION_GROUPING
AS
SELECT WORK_CENTER,MFG_GROUP, WORK_YEAR,WORK_WEEK,SIMULATION_DATE,SUM(OPERATION_QTY) OPERATION_QTY,SUM(OPERATION_HOUR) OPERATION_HOUR
FROM [dm_yg1_scm].FACT_SCM_CAPABALANCE_SIMULATION
GROUP BY WORK_CENTER,MFG_GROUP, WORK_YEAR,WORK_WEEK,SIMULATION_DATE