CREATE VIEW dm_yg1_scm.VW_FACT_SCM_SUPPLY_SIMULATION_TB_STATUS
as
SELECT 
A.*, 
T0.KTSCH AS T0_KTSCH, T0.WORK_DATE AS T0_WORK_DATE,
T1.KTSCH AS T1_KTSCH, T1.WORK_DATE AS T1_WORK_DATE,
T2.KTSCH AS T2_KTSCH, T2.WORK_DATE AS T2_WORK_DATE,
T3.KTSCH AS T3_KTSCH, T3.WORK_DATE AS T3_WORK_DATE,
T5.KTSCH AS T5_KTSCH, T5.WORK_DATE AS T5_WORK_DATE,
T6.KTSCH AS T6_KTSCH, T6.WORK_DATE AS T6_WORK_DATE,
T7.KTSCH AS T7_KTSCH, T7.WORK_DATE AS T7_WORK_DATE,
T8.KTSCH AS T8_KTSCH, T8.WORK_DATE AS T8_WORK_DATE,
T9.KTSCH AS T9_KTSCH, T9.WORK_DATE AS T9_WORK_DATE,
T10.KTSCH AS T10_KTSCH, T10.WORK_DATE AS T10_WORK_DATE,
T11.KTSCH AS T11_KTSCH, T11.WORK_DATE AS T11_WORK_DATE,
T12.KTSCH AS T12_KTSCH, T12.WORK_DATE AS T12_WORK_DATE,
T13.KTSCH AS T13_KTSCH, T13.WORK_DATE AS T13_WORK_DATE,
T14.KTSCH AS T14_KTSCH, T14.WORK_DATE AS T14_WORK_DATE,
T15.KTSCH AS T15_KTSCH, T15.WORK_DATE AS T15_WORK_DATE,
T16.KTSCH AS T16_KTSCH, T16.WORK_DATE AS T16_WORK_DATE,
T17.KTSCH AS T17_KTSCH, T17.WORK_DATE AS T17_WORK_DATE,
T18.KTSCH AS T18_KTSCH, T18.WORK_DATE AS T18_WORK_DATE,
T19.KTSCH AS T19_KTSCH, T19.WORK_DATE AS T19_WORK_DATE,
T20.KTSCH AS T20_KTSCH, T20.WORK_DATE AS T20_WORK_DATE
FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB A
LEFT OUTER JOIN 
(
SELECT A.CLIENT,A.WORK_CENTER_TEXT,A.PO,A.SAP_LOAD_DATE,A.WORK_DATE, B.[그룹명],KTSCH
FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A
JOIN 
DW_YG1.SCM.VW_WORKCENTER_GROUP B
ON A.WORK_CENTER_TEXT=B.KTSCH  WHERE [그룹명]='절단'
) 
T0 ON  1=1 -- A.CURRENT_TEXT_KEY=T0.KTSCH 
AND A.PO=T0.PO AND A.SAP_LOAD_DATE=T0.SAP_LOAD_DATE
AND A.CLIENT=T0.CLIENT
LEFT OUTER JOIN 
(
SELECT A.CLIENT,A.WORK_CENTER_TEXT,A.PO,A.SAP_LOAD_DATE,A.WORK_DATE, B.[그룹명],KTSCH
FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A
JOIN 
DW_YG1.SCM.VW_WORKCENTER_GROUP B
ON A.WORK_CENTER_TEXT=B.KTSCH  WHERE [그룹명]='포인트연삭'
) 
T1 ON  1=1 -- A.CURRENT_TEXT_KEY=T1.KTSCH 
AND A.PO=T1.PO AND A.SAP_LOAD_DATE=T1.SAP_LOAD_DATE
AND A.CLIENT=T1.CLIENT
LEFT OUTER JOIN 
(
SELECT A.CLIENT,A.WORK_CENTER_TEXT,A.PO,A.SAP_LOAD_DATE,A.WORK_DATE, B.[그룹명],KTSCH
FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A
JOIN 
DW_YG1.SCM.VW_WORKCENTER_GROUP B
ON A.WORK_CENTER_TEXT=B.KTSCH  WHERE [그룹명]='센터랩핑'
) 
T2 ON  1=1 -- A.CURRENT_TEXT_KEY=T2.KTSCH 
AND A.PO=T2.PO AND A.SAP_LOAD_DATE=T2.SAP_LOAD_DATE
AND A.CLIENT=T2.CLIENT
LEFT OUTER JOIN 
(
SELECT A.CLIENT,A.WORK_CENTER_TEXT,A.PO,A.SAP_LOAD_DATE,A.WORK_DATE, B.[그룹명],KTSCH
FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A
JOIN 
DW_YG1.SCM.VW_WORKCENTER_GROUP B
ON A.WORK_CENTER_TEXT=B.KTSCH  WHERE [그룹명]='센터레스'
) 
T3 ON  1=1 --   A.CURRENT_TEXT_KEY=T3.KTSCH 
 AND A.PO=T3.PO 
 AND A.SAP_LOAD_DATE=T3.SAP_LOAD_DATE
 AND A.CLIENT=T3.CLIENT
 
LEFT OUTER JOIN 
(
SELECT A.CLIENT,A.WORK_CENTER_TEXT,A.PO,A.SAP_LOAD_DATE,A.WORK_DATE, B.[그룹명],KTSCH
FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A
JOIN 
DW_YG1.SCM.VW_WORKCENTER_GROUP B
ON A.WORK_CENTER_TEXT=B.KTSCH  WHERE [그룹명]='백테이퍼'
) 
T5 ON  1=1 --   A.CURRENT_TEXT_KEY=T5.KTSCH 
 AND A.PO=T5.PO 
 AND A.SAP_LOAD_DATE=T5.SAP_LOAD_DATE
 AND A.CLIENT=T5.CLIENT
 
 
LEFT OUTER JOIN 
(
SELECT A.CLIENT,A.WORK_CENTER_TEXT,A.PO,A.SAP_LOAD_DATE,A.WORK_DATE, B.[그룹명],KTSCH
FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A
JOIN 
DW_YG1.SCM.VW_WORKCENTER_GROUP B
ON A.WORK_CENTER_TEXT=B.KTSCH  WHERE [그룹명]='볼황삭'
) 
T6 ON  1=1 --   A.CURRENT_TEXT_KEY=T6.KTSCH 
 AND A.PO=T6.PO 
 AND A.SAP_LOAD_DATE=T6.SAP_LOAD_DATE
 AND A.CLIENT=T6.CLIENT
  
LEFT OUTER JOIN 
(
SELECT A.CLIENT,A.WORK_CENTER_TEXT,A.PO,A.SAP_LOAD_DATE,A.WORK_DATE, B.[그룹명],KTSCH
FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A
JOIN 
DW_YG1.SCM.VW_WORKCENTER_GROUP B
ON A.WORK_CENTER_TEXT=B.KTSCH  WHERE [그룹명]='원통'
) 
T7 ON  1=1 --   A.CURRENT_TEXT_KEY=T7.KTSCH 
 AND A.PO=T7.PO 
 AND A.SAP_LOAD_DATE=T7.SAP_LOAD_DATE
 AND A.CLIENT=T7.CLIENT
 
  
LEFT OUTER JOIN 
(
SELECT A.CLIENT,A.WORK_CENTER_TEXT,A.PO,A.SAP_LOAD_DATE,A.WORK_DATE, B.[그룹명],KTSCH
FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A
JOIN 
DW_YG1.SCM.VW_WORKCENTER_GROUP B
ON A.WORK_CENTER_TEXT=B.KTSCH  WHERE [그룹명]='INFEED'
) 
T8 ON  1=1 --   A.CURRENT_TEXT_KEY=T8.KTSCH 
 AND A.PO=T8.PO 
 AND A.SAP_LOAD_DATE=T8.SAP_LOAD_DATE
 AND A.CLIENT=T8.CLIENT
 
 
  
LEFT OUTER JOIN 
(
SELECT A.CLIENT,A.WORK_CENTER_TEXT,A.PO,A.SAP_LOAD_DATE,A.WORK_DATE, B.[그룹명],KTSCH
FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A
JOIN 
DW_YG1.SCM.VW_WORKCENTER_GROUP B
ON A.WORK_CENTER_TEXT=B.KTSCH  WHERE [그룹명]='홈연삭'
) 
T9 ON  1=1 --   A.CURRENT_TEXT_KEY=T9.KTSCH 
 AND A.PO=T9.PO 
 AND A.SAP_LOAD_DATE=T9.SAP_LOAD_DATE
 AND A.CLIENT=T9.CLIENT
 
  
LEFT OUTER JOIN 
(
SELECT A.CLIENT,A.WORK_CENTER_TEXT,A.PO,A.SAP_LOAD_DATE,A.WORK_DATE, B.[그룹명],KTSCH
FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A
JOIN 
DW_YG1.SCM.VW_WORKCENTER_GROUP B
ON A.WORK_CENTER_TEXT=B.KTSCH  WHERE [그룹명]='TANG'
) 
T10 ON  1=1 --   A.CURRENT_TEXT_KEY=T10.KTSCH 
 AND A.PO=T10.PO 
 AND A.SAP_LOAD_DATE=T10.SAP_LOAD_DATE
 AND A.CLIENT=T10.CLIENT
 
LEFT OUTER JOIN 
(
SELECT A.CLIENT,A.WORK_CENTER_TEXT,A.PO,A.SAP_LOAD_DATE,A.WORK_DATE, B.[그룹명],KTSCH
FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A
JOIN 
DW_YG1.SCM.VW_WORKCENTER_GROUP B
ON A.WORK_CENTER_TEXT=B.KTSCH  WHERE [그룹명]='원척킹'
) 
T11 ON  1=1 --  
 AND A.PO=T11.PO 
 AND A.SAP_LOAD_DATE=T11.SAP_LOAD_DATE
 AND A.CLIENT=T11.CLIENT
 
 
LEFT OUTER JOIN 
(
SELECT A.CLIENT,A.WORK_CENTER_TEXT,A.PO,A.SAP_LOAD_DATE,A.WORK_DATE, B.[그룹명],KTSCH
FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A
JOIN 
DW_YG1.SCM.VW_WORKCENTER_GROUP B
ON A.WORK_CENTER_TEXT=B.KTSCH  WHERE [그룹명]='밑날연삭'
) 
T12 ON  1=1 --   --A.CURRENT_TEXT_KEY=T12.KTSCH 
 AND A.PO=T12.PO 
 AND A.SAP_LOAD_DATE=T12.SAP_LOAD_DATE
 AND A.CLIENT=T12.CLIENT
 
 
LEFT OUTER JOIN 
(
SELECT A.CLIENT,A.WORK_CENTER_TEXT,A.PO,A.SAP_LOAD_DATE,A.WORK_DATE, B.[그룹명],KTSCH
FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A
JOIN 
DW_YG1.SCM.VW_WORKCENTER_GROUP B
ON A.WORK_CENTER_TEXT=B.KTSCH  WHERE [그룹명]='호닝[MANUAL]'
) 
T13 ON  1=1 --   --A.CURRENT_TEXT_KEY=T13.KTSCH 
 AND A.PO=T13.PO 
 AND A.SAP_LOAD_DATE=T13.SAP_LOAD_DATE
 AND A.CLIENT=T13.CLIENT
 LEFT OUTER JOIN 
(
SELECT A.CLIENT,A.WORK_CENTER_TEXT,A.PO,A.SAP_LOAD_DATE,A.WORK_DATE, B.[그룹명],KTSCH
FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A
JOIN 
DW_YG1.SCM.VW_WORKCENTER_GROUP B
ON A.WORK_CENTER_TEXT=B.KTSCH  WHERE [그룹명]='TOYO폴리싱'
) 
T14 ON  1=1 --A.CURRENT_TEXT_KEY=T14.KTSCH 
 AND A.PO=T14.PO 
 AND A.SAP_LOAD_DATE=T14.SAP_LOAD_DATE
 AND A.CLIENT=T14.CLIENT
 
 LEFT OUTER JOIN 
(
SELECT A.CLIENT,A.WORK_CENTER_TEXT,A.PO,A.SAP_LOAD_DATE,A.WORK_DATE, B.[그룹명],KTSCH
FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A
JOIN 
DW_YG1.SCM.VW_WORKCENTER_GROUP B
ON A.WORK_CENTER_TEXT=B.KTSCH  WHERE [그룹명]='평면연삭'
) 
T15 ON  1=1 --  -- A.CURRENT_TEXT_KEY=T15.KTSCH 
 AND A.PO=T15.PO 
 AND A.SAP_LOAD_DATE=T15.SAP_LOAD_DATE
 AND A.CLIENT=T15.CLIENT
  
 LEFT OUTER JOIN 
(
SELECT A.CLIENT,A.WORK_CENTER_TEXT,A.PO,A.SAP_LOAD_DATE,A.WORK_DATE, B.[그룹명],KTSCH
FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A
JOIN 
DW_YG1.SCM.VW_WORKCENTER_GROUP B
ON A.WORK_CENTER_TEXT=B.KTSCH  WHERE [그룹명]='슬롯연삭'
) 
T16 ON  1=1   --A.CURRENT_TEXT_KEY=T16.KTSCH 
 AND A.PO=T16.PO 
 AND A.SAP_LOAD_DATE=T16.SAP_LOAD_DATE
 AND A.CLIENT=T16.CLIENT
 
 LEFT OUTER JOIN 
(
SELECT A.CLIENT,A.WORK_CENTER_TEXT,A.PO,A.SAP_LOAD_DATE,A.WORK_DATE, B.[그룹명],KTSCH
FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A
JOIN 
DW_YG1.SCM.VW_WORKCENTER_GROUP B
ON A.WORK_CENTER_TEXT=B.KTSCH  WHERE [그룹명]='NECK'
) 
T17 ON  1=1 --A.CURRENT_TEXT_KEY=T17.KTSCH 
 AND A.PO=T17.PO 
 AND A.SAP_LOAD_DATE=T17.SAP_LOAD_DATE
 AND A.CLIENT=T17.CLIENT
 
 
 LEFT OUTER JOIN 
(
SELECT A.CLIENT,A.WORK_CENTER_TEXT,A.PO,A.SAP_LOAD_DATE,A.WORK_DATE, B.[그룹명],KTSCH
FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A
JOIN 
DW_YG1.SCM.VW_WORKCENTER_GROUP B
ON A.WORK_CENTER_TEXT=B.KTSCH  WHERE [그룹명]='여유면연삭'
) 
T18 ON  1=1 --A.CURRENT_TEXT_KEY=T18.KTSCH 
 AND A.PO=T18.PO 
 AND A.SAP_LOAD_DATE=T18.SAP_LOAD_DATE
 AND A.CLIENT=T18.CLIENT
 
 
 LEFT OUTER JOIN 
(
SELECT A.CLIENT,A.WORK_CENTER_TEXT,A.PO,A.SAP_LOAD_DATE,A.WORK_DATE, B.[그룹명],KTSCH
FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A
JOIN 
DW_YG1.SCM.VW_WORKCENTER_GROUP B
ON A.WORK_CENTER_TEXT=B.KTSCH  WHERE [그룹명]='호닝[Cleaning]'
) 
T19 ON  1=1 -- A.CURRENT_TEXT_KEY=T19.KTSCH 
 AND A.PO=T19.PO 
 AND A.SAP_LOAD_DATE=T19.SAP_LOAD_DATE
 AND A.CLIENT=T19.CLIENT
 
 LEFT OUTER JOIN 
(
SELECT A.CLIENT,A.WORK_CENTER_TEXT,A.PO,A.SAP_LOAD_DATE,A.WORK_DATE, B.[그룹명],KTSCH
FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_ROUTING A
JOIN 
DW_YG1.SCM.VW_WORKCENTER_GROUP B
ON A.WORK_CENTER_TEXT=B.KTSCH  WHERE [그룹명]='세척'
) 
T20 ON  1=1 --   A.CURRENT_TEXT_KEY=T20.KTSCH 
 AND A.PO=T20.PO 
 AND A.SAP_LOAD_DATE=T20.SAP_LOAD_DATE
 AND A.CLIENT=T19.CLIENT