COLUMN: CLIENT int NOT NULL
COLUMN: SAP_LOAD_DATE int NOT NULL
COLUMN: LT_VARIANT numeric NULL
COLUMN: LT_SIGMA numeric NULL
COLUMN: LT_EXPECTATION numeric NULL
COLUMN: LT_FULFILLMENT_RATE numeric NULL
COLUMN: ETL_TIME date NOT NULL