USE [DM_YG1]
GO

/****** Object:  StoredProcedure [dm_yg1_scm].[PROC_FACT_SCM_CAPABALANCE_SIMULATION]    Script Date: 2025-07-25 오후 12:39:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





/****************************************************************************************************************

******************************************************************************************************************/
CREATE PROCEDURE [dm_yg1_scm].[PROC_FACT_SCM_CAPABALANCE_SIMULATION]
AS
BEGIN

	
	--공통변수
	DECLARE @SP_START_EXEC		DATETIME = GETDATE()	-- SP 실행시작시간
	DECLARE @INSERT_CNT	INT = 0			-- INSERT 건수
	DECLARE @UPDATE_CNT	INT = 0			-- UPDATE 건수
	DECLARE @DELETE_CNT	INT = 0			-- DELETE 건수
	DECLARE	@TABLE_NM	VARCHAR(50) = 'PROC_FACT_SCM_CAPABALANCE_SIMULATION'	-- TARGET TABLE NAME
	DECLARE @ERR_MSG	VARCHAR(4000)
	DECLARE @ERR_NUM	NVARCHAR(20)
	DECLARE @ERR_LINE	INT
	DECLARE @ERSDA INT =(SELECT MAX(ERSDA) FROM  DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB WITH(NOLOCK))
	
	
	
	DECLARE @COMPANY_CD	VARCHAR(12)	= '1000'	-- 회사코드 (SAP 필드명 : BUKRS) 

	BEGIN TRY

		-- 
		DELETE FROM dm_yg1_scm.FACT_SCM_CAPABALANCE_SIMULATION
		WHERE [SAP_LOAD_DATE]=@ERSDA
		SET @DELETE_CNT=@@ROWCOUNT

		INSERT INTO [dm_yg1_scm].[FACT_SCM_CAPABALANCE_SIMULATION]
           (
            [CLIENT]
		   ,[SAP_LOAD_DATE]
		   ,[WORK_CENTER]
           ,[MFG_GROUP]
           ,[OPERATION_HOUR]
           ,[WORKCENTER_NAME]
           ,[OPERATION_QTY]
           ,[WORK_YEAR]
           ,[WORK_WEEK]
           ,[IS_GRAPH]
           ,[ETL_TIME])

		   		SELECT 
		CLIENT,
		SAP_LOAD_DATE,
		WORK_CENTER,
		MFG_GROUP,
		SUM(LT) [OPERATION_HOUR],
		LTXA1 [WORKCENTER_NAME],
		SUM(OPERATION_QTY) [OPERATION_QTY],
		WORK_YEAR,
		WORK_WEEK,
		NULL [IS_GRAPH],
		GETDATE() [ETL_TIME]
		FROM  [dm_yg1_scm].[FACT_SCM_CAPABALANCE_ORDER] WITH(NOLOCK)
		WHERE [SAP_LOAD_DATE]=@ERSDA

		GROUP BY 
		CLIENT,
		SAP_LOAD_DATE,
		WORK_CENTER,
		MFG_GROUP,
		LTXA1,
		WORK_YEAR,
		WORK_WEEK

	

		SET @INSERT_CNT	= @@ROWCOUNT

		INSERT INTO DW_YG1.DBO.TB_ETL_LOG
					(DB_NM			, SP_NM							, TABLE_NM		, START_DATE		, END_DATE		
					, INSERT_CNT	, DELETE_CNT	, UPDATE_CNT	, SUCCEESS_YN	, ERR_MSG			, ERR_NUM	, ERR_LINE)
			VALUES	(DB_NAME()		, OBJECT_NAME(@@PROCID)			, @TABLE_NM		, @SP_START_EXEC	, GETDATE()
					, @INSERT_CNT	, @DELETE_CNT	
					, @UPDATE_CNT	, 'Y'			, NULL				, NULL		, NULL)
			
	END TRY

	BEGIN CATCH
			
		SET @ERR_MSG	= ERROR_MESSAGE()
		SET @ERR_NUM	= ERROR_NUMBER()
		SET @ERR_LINE	= ERROR_LINE()

		PRINT	@ERR_MSG
		
		INSERT INTO DW_YG1.DBO.TB_ETL_LOG
				(DB_NM			, SP_NM							, TABLE_NM		, START_DATE		, END_DATE		
				, INSERT_CNT	, DELETE_CNT	, UPDATE_CNT	, SUCCEESS_YN	, ERR_MSG			, ERR_NUM		, ERR_LINE)
		VALUES	(DB_NAME()		, OBJECT_NAME(@@PROCID)			, @TABLE_NM		, @SP_START_EXEC	, GETDATE()
				, @INSERT_CNT	, @DELETE_CNT	, @UPDATE_CNT	, 'N'			, ERROR_MESSAGE()	, ERROR_NUMBER(), ERROR_LINE());
	END CATCH
END
GO


