USE [DM_YG1]
GO

/****** Object:  StoredProcedure [dm_yg1_scm].[PROC_FACT_SCM_SUPPLY_SIMULATION_TB_REPORT]    Script Date: 2025-07-25 오후 12:41:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






/****************************************************************************************************************
SP 명		: PROC_FACT_SCM_SUPPLY_SIMULATION_TB
SP 제목		: 조달생산가시화 테이블 
최초작성자	: 최은수
최초작성일	: 2024.10.25


	
******************************************************************************************************************/
CREATE PROCEDURE [dm_yg1_scm].[PROC_FACT_SCM_SUPPLY_SIMULATION_TB_REPORT]
AS
BEGIN

	
	--공통변수
	DECLARE @SP_START_EXEC		DATETIME = GETDATE()	-- SP 실행시작시간
	DECLARE @INSERT_CNT	INT = 0			-- INSERT 건수
	DECLARE @UPDATE_CNT	INT = 0			-- UPDATE 건수
	DECLARE @DELETE_CNT	INT = 0			-- DELETE 건수
	DECLARE	@TABLE_NM	VARCHAR(50) = 'FACT_SCM_SUPPLY_SIMULATION_TB_REPORT'	-- TARGET TABLE NAME
	DECLARE @ERR_MSG	VARCHAR(4000)
	DECLARE @ERR_NUM	NVARCHAR(20)
	DECLARE @ERR_LINE	INT

	
	
	DECLARE @COMPANY_CD	VARCHAR(12)	= '1000'	-- 회사코드 (SAP 필드명 : BUKRS) 

	BEGIN TRY

	DELETE FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_REPORT
	WHERE SAP_LOAD_DATE IN (SELECT ERSDA
	FROM DW_YG1.scm.TB_DW_DIM_ZDWT005_COOIS
	WHERE ETL_DATE=(SELECT MAX(ETL_DATE) FROM  DW_YG1.scm.TB_DW_DIM_ZDWT005_COOIS)
	)
	SET @DELETE_CNT=@@ROWCOUNT


	INSERT INTO DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_REPORT
	SELECT 
	A.MANDT AS CLIENT,
	A.ERSDA AS ERSDA,
	A.AUFNR AS PO,
	A.MATNR AS MATERIAL,
	B.MATNR1 AS BOM_MATERIAL,
	B.KTSCH AS CURRENT_TEXT_KEY,
	B.KTEXT,
	WC.[GROUP],
	B.SSELD AS CURRENT_WORK_INPUT_DATE,
	CASE WHEN B.SSELD>'00000000' THEN  '투입'
	ELSE '미투입' END as "OPER_INPUT_YN",
	PSMNG AS QTY,
	INV.BDMNG AS REQMTS_QTY,
	BOM.MTART,
	CASE WHEN BOM.MTART='ROH' THEN '원자재'
	WHEN BOM.MTART='HALB' OR BOM.MTART='FERT' THEN '반제품'
	WHEN B.MATNR=B.MATNR1 THEN '재연마' 
	ELSE '재연마' END AS BOM_TYPE ,
	A.MATKL,
	CASE WHEN P.AUFNR IS NOT NULL THEN '투입(GMPS)'
	ELSE NULL END AS "BOM_INPUT_YN",
	SUP.PLAN_RDD AS RDD,
	SUP.AUDAT_RDD as [RDD_6주],
	DATEPART(WEEK,SUP.PLAN_RDD) AS RDD_WEEK,
	convert(varchar,B.AUFNR)+'/'+convert(varchar,B.GLTRP) AS OPERATION_KEY,
	CASE WHEN A.STAT LIKE '%GMPS%' THEN '투입(GMPS)' ELSE '자재출고' END AS [SYSTEM_STATUS],
	NULL,--INV.CHARG  AS BATCH,
	INV.MENGE AS QTY,
	NULL,--INV.LGORT AS FROM_LOC,
	NULL,--INV.UMLGO AS TO_LOC,

	@SP_START_EXEC AS ETL_DATE,
	T0.KTSCH	AS T0_KTSCH,	T0.GSTRI	AS T0_WORK_DATE,
	T1.KTSCH	AS T1_KTSCH,	T1.GSTRI	AS T1_WORK_DATE,
	T2.KTSCH	AS T2_KTSCH,	T2.GSTRI	AS T2_WORK_DATE,
	T3.KTSCH	AS T3_KTSCH,	T3.GSTRI	AS T3_WORK_DATE,
	T4.KTSCH	AS T3_KTSCH,	T4.GSTRI	AS T3_WORK_DATE,
	T5.KTSCH	AS T5_KTSCH,	T5.GSTRI	AS T5_WORK_DATE,
	T6.KTSCH	AS T6_KTSCH,	T6.GSTRI	AS T6_WORK_DATE,
	T7.KTSCH	AS T7_KTSCH,	T7.GSTRI	AS T7_WORK_DATE,
	T8.KTSCH	AS T8_KTSCH,	T8.GSTRI	AS T8_WORK_DATE,
	T9.KTSCH	AS T9_KTSCH,	T9.GSTRI	AS T9_WORK_DATE,
	T10.KTSCH	AS T10_KTSCH,	T10.GSTRI	AS T10_WORK_DATE,
	T11.KTSCH	AS T11_KTSCH,	T11.GSTRI	AS T11_WORK_DATE,
	T12.KTSCH	AS T12_KTSCH,	T12.GSTRI	AS T12_WORK_DATE,
	T13.KTSCH	AS T13_KTSCH,	T13.GSTRI	AS T13_WORK_DATE,
	T14.KTSCH	AS T14_KTSCH,	T14.GSTRI	AS T14_WORK_DATE,
	T15.KTSCH	AS T15_KTSCH,	T15.GSTRI	AS T15_WORK_DATE,
	T16.KTSCH	AS T16_KTSCH,	T16.GSTRI	AS T16_WORK_DATE,
	T17.KTSCH	AS T17_KTSCH,	T17.GSTRI	AS T17_WORK_DATE,
	T18.KTSCH	AS T18_KTSCH,	T18.GSTRI	AS T18_WORK_DATE,
	T19.KTSCH	AS T19_KTSCH,	T19.GSTRI	AS T19_WORK_DATE,
	T20.KTSCH	AS T20_KTSCH,	T20.GSTRI	AS T20_WORK_DATE
	
	
	FROM (SELECT *
	FROM DW_YG1.scm.TB_DW_DIM_ZDWT005_COOIS WITH(NOLOCK)
	WHERE DISPO NOT LIKE 'CO%'
	) A
	LEFT OUTER JOIN DW_YG1.scm.TB_DW_FACT_ZDWT006_Z25PP031 B WITH(NOLOCK)
	ON  1=1
		AND A.MANDT=B.MANDT
		AND A.ERSDA=B.ERSDA
		AND A.AUFNR=B.AUFNR
	LEFT OUTER JOIN DW_YG1.scm.TB_SCM_WORKCENTER C WITH(NOLOCK)
	ON B.KTSCH=C.StdTextKey
	LEFT OUTER JOIN DW_YG1.DBO.TB_DW_DIM_MARA BOM WITH(NOLOCK)
	ON  1=1
		AND B.MATNR1=BOM.MATNR 
		AND B.MANDT=BOM.MANDT
	LEFT OUTER JOIN (
	SELECT DISTINCT MANDT,AUFNR ,ERSDA
	FROM DW_YG1.scm.TB_DW_FACT_ZDWT009_Z25MM001 WITH(NOLOCK)) P
	ON 1=1
		AND A.MANDT=B.MANDT 
		AND A.AUFNR=P.AUFNR 
		AND A.ERSDA=P.ERSDA
	LEFT OUTER JOIN (SELECT DISTINCT  MANDT,ERSDA,AUFNR,MATNR,AUDAT,AUDAT_RDD,PLAN_RDD
FROM DW_YG1.SCM.TB_DW_FACT_SCM_SUPPLY_SIMULATION_RESULT WITH(NOLOCK) ) SUP
	ON  1=1
		AND A.AUFNR=SUP.AUFNR 
		AND A.MANDT=SUP.MANDT 
		AND A.ERSDA=SUP.ERSDA -- AND SUP.CHECK_TYPE IS NULL
	LEFT OUTER JOIN DW_YG1.scm.TB_SCM_WORKCENTER WC WITH(NOLOCK)
	ON B.KTSCH=WC.StdTextKey
	LEFT OUTER JOIN ( SELECT MANDT,ERSDA,MATNR,AUFNR,SUM(MENGE) AS MENGE, SUM(BDMNG) AS BDMNG
						FROM DW_YG1.scm.TB_DW_FACT_ZDWT009_Z25MM001 WITH(NOLOCK)
						GROUP BY AUFNR,MANDT,ERSDA,MATNR) as INV
	ON  1=1
		AND A.ERSDA=INV.ERSDA 
		AND A.MANDT=INV.MANDT 
		AND A.AUFNR=INV.AUFNR 
		AND A.IDNRK=INV.MATNR
	
	LEFT OUTER JOIN 
	(
	SELECT distinct A.MANDT,A.KTSCH,A.AUFNR,A.ERSDA,A.GSTRI, B.[그룹명]

	FROM DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB A WITH(NOLOCK)
	JOIN 
	DW_YG1.SCM.VW_WORKCENTER_GROUP B WITH(NOLOCK)
	ON A.KTSCH=B.KTSCH  WHERE [그룹명]='절단'
	) 
	T0 ON  1=1 -- A.CURRENT_TEXT_KEY=T0.KTSCH 
		AND A.AUFNR=T0.AUFNR 
		AND A.ERSDA=T0.ERSDA
		AND A.MANDT=T0.MANDT
	LEFT OUTER JOIN 
	(
	SELECT distinct A.MANDT,A.KTSCH,A.AUFNR,A.ERSDA,A.GSTRI, B.[그룹명]

	FROM DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB A WITH(NOLOCK)
	JOIN 
	DW_YG1.SCM.VW_WORKCENTER_GROUP B WITH(NOLOCK)
	ON A.KTSCH=B.KTSCH  WHERE [그룹명]='포인트연삭'
	) 
	T1 ON  1=1 -- A.CURRENT_TEXT_KEY=T1.KTSCH 
		AND A.AUFNR=T1.AUFNR 
		AND A.ERSDA=T1.ERSDA
		AND A.MANDT=T1.MANDT

	LEFT OUTER JOIN 
	(
	SELECT distinct A.MANDT,A.KTSCH,A.AUFNR,A.ERSDA,A.GSTRI, B.[그룹명]

	FROM DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB A WITH(NOLOCK)
	JOIN 
	DW_YG1.SCM.VW_WORKCENTER_GROUP B WITH(NOLOCK)
	ON A.KTSCH=B.KTSCH  WHERE [그룹명]='센터연삭'
	) 
	T2 ON  1=1 -- A.CURRENT_TEXT_KEY=T2.KTSCH 
		AND A.AUFNR=T2.AUFNR 
		AND A.ERSDA=T2.ERSDA
		AND A.MANDT=T2.MANDT


	LEFT OUTER JOIN 
	(
	SELECT distinct A.MANDT,A.KTSCH,A.AUFNR,A.ERSDA,A.GSTRI, B.[그룹명]

	FROM DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB A WITH(NOLOCK)
	JOIN 
	DW_YG1.SCM.VW_WORKCENTER_GROUP B WITH(NOLOCK)
	ON A.KTSCH=B.KTSCH  WHERE [그룹명]='센터랩핑'
	) 
	T3 ON  1=1 --   A.CURRENT_TEXT_KEY=T3.KTSCH 
		AND A.AUFNR=T3.AUFNR 
		AND A.ERSDA=T3.ERSDA
		AND A.MANDT=T3.MANDT
	LEFT OUTER JOIN 
	(
	SELECT distinct A.MANDT,A.KTSCH,A.AUFNR,A.ERSDA,A.GSTRI, B.[그룹명]

	FROM DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB A WITH(NOLOCK)
	JOIN 
	DW_YG1.SCM.VW_WORKCENTER_GROUP B WITH(NOLOCK)
	ON A.KTSCH=B.KTSCH  WHERE [그룹명]='센터레스'
	) 
	T4 ON  1=1 --   A.CURRENT_TEXT_KEY=T3.KTSCH 
		AND A.AUFNR=T4.AUFNR 
		AND A.ERSDA=T4.ERSDA
		AND A.MANDT=T4.MANDT

	LEFT OUTER JOIN 
	(
	SELECT distinct A.MANDT,A.KTSCH,A.AUFNR,A.ERSDA,A.GSTRI, B.[그룹명]

	FROM DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB A WITH(NOLOCK)
	JOIN 
	DW_YG1.SCM.VW_WORKCENTER_GROUP B WITH(NOLOCK)
	ON A.KTSCH=B.KTSCH  WHERE [그룹명]='백테이퍼'
	) 
	T5 ON  1=1 --   A.CURRENT_TEXT_KEY=T5.KTSCH 
		AND A.AUFNR=T5.AUFNR 
		AND A.ERSDA=T5.ERSDA
		AND A.MANDT=T5.MANDT
	
	
	LEFT OUTER JOIN 
	(
	SELECT distinct A.MANDT,A.KTSCH,A.AUFNR,A.ERSDA,A.GSTRI, B.[그룹명]

	FROM DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB A WITH(NOLOCK)
	JOIN 
	DW_YG1.SCM.VW_WORKCENTER_GROUP B WITH(NOLOCK)
	ON A.KTSCH=B.KTSCH  WHERE [그룹명]='볼황삭'
	) 
	T6 ON  1=1 --   A.CURRENT_TEXT_KEY=T6.KTSCH 
		AND A.AUFNR=T6.AUFNR 
		AND A.ERSDA=T6.ERSDA
		AND A.MANDT=T6.MANDT

		
	LEFT OUTER JOIN 
	(
	SELECT distinct A.MANDT,A.KTSCH,A.AUFNR,A.ERSDA,A.GSTRI, B.[그룹명]

	FROM DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB A WITH(NOLOCK)
	JOIN 
	DW_YG1.SCM.VW_WORKCENTER_GROUP B WITH(NOLOCK)
	ON A.KTSCH=B.KTSCH  WHERE [그룹명]='원통'
	) 
	T7 ON  1=1 --   A.CURRENT_TEXT_KEY=T7.KTSCH 
		AND A.AUFNR=T7.AUFNR 
		AND A.ERSDA=T7.ERSDA
		AND A.MANDT=T7.MANDT


	
		
	LEFT OUTER JOIN 
	(
	SELECT distinct A.MANDT,A.KTSCH,A.AUFNR,A.ERSDA,A.GSTRI, B.[그룹명]

	FROM DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB A WITH(NOLOCK)
	JOIN 
	DW_YG1.SCM.VW_WORKCENTER_GROUP B WITH(NOLOCK)
	ON A.KTSCH=B.KTSCH  WHERE [그룹명]='INFEED'
	) 
	T8 ON  1=1 --   A.CURRENT_TEXT_KEY=T8.KTSCH 
		AND A.AUFNR=T8.AUFNR 
		AND A.ERSDA=T8.ERSDA
		AND A.MANDT=T8.MANDT

	
	
		
	LEFT OUTER JOIN 
	(
	SELECT distinct A.MANDT,A.KTSCH,A.AUFNR,A.ERSDA,A.GSTRI, B.[그룹명]

	FROM DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB A WITH(NOLOCK)
	JOIN 
	DW_YG1.SCM.VW_WORKCENTER_GROUP B WITH(NOLOCK)
	ON A.KTSCH=B.KTSCH  WHERE [그룹명]='홈연삭'
	) 
	T9 ON  1=1 --   A.CURRENT_TEXT_KEY=T9.KTSCH 
		AND A.AUFNR=T9.AUFNR 
		AND A.ERSDA=T9.ERSDA
		AND A.MANDT=T9.MANDT
	
		
	LEFT OUTER JOIN 
	(
	SELECT distinct A.MANDT,A.KTSCH,A.AUFNR,A.ERSDA,A.GSTRI, B.[그룹명]

	FROM DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB A WITH(NOLOCK)
	JOIN 
	DW_YG1.SCM.VW_WORKCENTER_GROUP B WITH(NOLOCK)
	ON A.KTSCH=B.KTSCH  WHERE [그룹명]='TANG'
	) 
	T10 ON  1=1 --   A.CURRENT_TEXT_KEY=T10.KTSCH 
		AND A.AUFNR=T10.AUFNR 
		AND A.ERSDA=T10.ERSDA
		AND A.MANDT=T10.MANDT

	
	LEFT OUTER JOIN 
	(
	SELECT distinct A.MANDT,A.KTSCH,A.AUFNR,A.ERSDA,A.GSTRI, B.[그룹명]

	FROM DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB A WITH(NOLOCK)
	JOIN 
	DW_YG1.SCM.VW_WORKCENTER_GROUP B WITH(NOLOCK)
	ON A.KTSCH=B.KTSCH  WHERE [그룹명]='원척킹'
	) 
	T11 ON  1=1 --  
		AND A.AUFNR=T11.AUFNR 
		AND A.ERSDA=T11.ERSDA
		AND A.MANDT=T11.MANDT
	
	
	LEFT OUTER JOIN 
	(
	SELECT distinct A.MANDT,A.KTSCH,A.AUFNR,A.ERSDA,A.GSTRI, B.[그룹명]

	FROM DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB A WITH(NOLOCK)
	JOIN 
	DW_YG1.SCM.VW_WORKCENTER_GROUP B WITH(NOLOCK)
	ON A.KTSCH=B.KTSCH  WHERE [그룹명]='밑날연삭'
	) 
	T12 ON  1=1 --   --A.CURRENT_TEXT_KEY=T12.KTSCH 
		AND A.AUFNR=T12.AUFNR 
		AND A.ERSDA=T12.ERSDA
		AND A.MANDT=T12.MANDT
	
	
	LEFT OUTER JOIN 
	(
	SELECT distinct A.MANDT,A.KTSCH,A.AUFNR,A.ERSDA,A.GSTRI, B.[그룹명]

	FROM DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB A WITH(NOLOCK)
	JOIN 
	DW_YG1.SCM.VW_WORKCENTER_GROUP B WITH(NOLOCK)
	ON A.KTSCH=B.KTSCH  WHERE [그룹명]='호닝[MANUAL]'
	) 
	T13 ON  1=1 --   --A.CURRENT_TEXT_KEY=T13.KTSCH 
		AND A.AUFNR=T13.AUFNR 
		AND A.ERSDA=T13.ERSDA
		AND A.MANDT=T13.MANDT

		LEFT OUTER JOIN 
	(
	SELECT distinct  A.MANDT,A.KTSCH,A.AUFNR,A.ERSDA,A.GSTRI, B.[그룹명]

	FROM DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB A WITH(NOLOCK)
	JOIN 
	DW_YG1.SCM.VW_WORKCENTER_GROUP B WITH(NOLOCK)
	ON A.KTSCH=B.KTSCH  WHERE [그룹명]='TOYO폴리싱'
	) 
	T14 ON  1=1 --A.CURRENT_TEXT_KEY=T14.KTSCH 
		AND A.AUFNR=T14.AUFNR 
		AND A.ERSDA=T14.ERSDA
		AND A.MANDT=T14.MANDT


	
		LEFT OUTER JOIN 
	(
	SELECT distinct  A.MANDT,A.KTSCH,A.AUFNR,A.ERSDA,A.GSTRI, B.[그룹명]

	FROM DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB A WITH(NOLOCK)
	JOIN 
	DW_YG1.SCM.VW_WORKCENTER_GROUP B WITH(NOLOCK)
	ON A.KTSCH=B.KTSCH  WHERE [그룹명]='평면연삭'
	) 
	T15 ON  1=1 --  -- A.CURRENT_TEXT_KEY=T15.KTSCH 
		AND A.AUFNR=T15.AUFNR 
		AND A.ERSDA=T15.ERSDA
		AND A.MANDT=T15.MANDT
		
		LEFT OUTER JOIN 
	(
	SELECT distinct  A.MANDT,A.KTSCH,A.AUFNR,A.ERSDA,A.GSTRI, B.[그룹명]

	FROM DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB A WITH(NOLOCK)
	JOIN 
	DW_YG1.SCM.VW_WORKCENTER_GROUP B WITH(NOLOCK)
	ON A.KTSCH=B.KTSCH  WHERE [그룹명]='슬롯연삭'
	) 
	T16 ON  1=1   --A.CURRENT_TEXT_KEY=T16.KTSCH 
		AND A.AUFNR=T16.AUFNR 
		AND A.ERSDA=T16.ERSDA
		AND A.MANDT=T16.MANDT


	
		LEFT OUTER JOIN 
	(
	SELECT distinct  A.MANDT,A.KTSCH,A.AUFNR,A.ERSDA,A.GSTRI, B.[그룹명]

	FROM DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB A WITH(NOLOCK)
	JOIN 
	DW_YG1.SCM.VW_WORKCENTER_GROUP B WITH(NOLOCK)
	ON A.KTSCH=B.KTSCH  WHERE [그룹명]='NECK'
	) 
	T17 ON  1=1 --A.CURRENT_TEXT_KEY=T17.KTSCH 
		AND A.AUFNR=T17.AUFNR 
		AND A.ERSDA=T17.ERSDA
		AND A.MANDT=T17.MANDT
	
	
		LEFT OUTER JOIN 
	(
	SELECT distinct  A.MANDT,A.KTSCH,A.AUFNR,A.ERSDA,A.GSTRI, B.[그룹명]

	FROM DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB A WITH(NOLOCK)
	JOIN 
	DW_YG1.SCM.VW_WORKCENTER_GROUP B WITH(NOLOCK)
	ON A.KTSCH=B.KTSCH  WHERE [그룹명]='여유면연삭'
	) 
	T18 ON  1=1 --A.CURRENT_TEXT_KEY=T18.KTSCH 
		AND A.AUFNR=T18.AUFNR 
		AND A.ERSDA=T18.ERSDA
		AND A.MANDT=T18.MANDT
	
	
		LEFT OUTER JOIN 
	(
	SELECT distinct  A.MANDT,A.KTSCH,A.AUFNR,A.ERSDA,A.GSTRI, B.[그룹명]

	FROM DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB A WITH(NOLOCK)
	JOIN 
	DW_YG1.SCM.VW_WORKCENTER_GROUP B WITH(NOLOCK)
	ON A.KTSCH=B.KTSCH  WHERE [그룹명]='호닝[Cleaning]'
	) 
	T19 ON  1=1 -- A.CURRENT_TEXT_KEY=T19.KTSCH 
		AND A.AUFNR=T19.AUFNR 
		AND A.ERSDA=T19.ERSDA
		AND A.MANDT=T19.MANDT
	
		LEFT OUTER JOIN 
	(
	SELECT distinct  A.MANDT,A.KTSCH,A.AUFNR,A.ERSDA,A.GSTRI, B.[그룹명]

	FROM DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB A WITH(NOLOCK)
	JOIN 
	DW_YG1.SCM.VW_WORKCENTER_GROUP B WITH(NOLOCK)
	ON A.KTSCH=B.KTSCH  WHERE [그룹명]='세척'
	) 
	T20 ON  1=1 --   A.CURRENT_TEXT_KEY=T20.KTSCH 
		AND A.AUFNR=T20.AUFNR 
		AND A.ERSDA=T20.ERSDA
		AND A.MANDT=T20.MANDT
	WHERE A.ETL_DATE=(SELECT MAX(ETL_DATE) FROM  DW_YG1.scm.TB_DW_DIM_ZDWT005_COOIS)

	SET @INSERT_CNT=@@ROWCOUNT





		SET @INSERT_CNT	= @@ROWCOUNT

		INSERT INTO DW_YG1.DBO.TB_ETL_LOG
					(DB_NM			, SP_NM							, TABLE_NM		, START_DATE		, END_DATE		
					, INSERT_CNT	, DELETE_CNT	, UPDATE_CNT	, SUCCEESS_YN	, ERR_MSG			, ERR_NUM	, ERR_LINE)
			VALUES	(DB_NAME()		, OBJECT_NAME(@@PROCID)			, @TABLE_NM		, @SP_START_EXEC	, GETDATE()
					, @INSERT_CNT	, @DELETE_CNT	, @UPDATE_CNT	, 'Y'			, NULL				, NULL		, NULL)
			
	END TRY

	BEGIN CATCH
			
		SET @ERR_MSG	= ERROR_MESSAGE()
		SET @ERR_NUM	= ERROR_NUMBER()
		SET @ERR_LINE	= ERROR_LINE()

		PRINT	@ERR_MSG
		
		INSERT INTO DW_YG1.DBO.TB_ETL_LOG
				(DB_NM			, SP_NM							, TABLE_NM		, START_DATE		, END_DATE		
				, INSERT_CNT	, DELETE_CNT	, UPDATE_CNT	, SUCCEESS_YN	, ERR_MSG			, ERR_NUM		, ERR_LINE)
		VALUES	(DB_NAME()		, OBJECT_NAME(@@PROCID)			, @TABLE_NM		, @SP_START_EXEC	, GETDATE()
				, @INSERT_CNT	, @DELETE_CNT	, @UPDATE_CNT	, 'N'			, ERROR_MESSAGE()	, ERROR_NUMBER(), ERROR_LINE());
	END CATCH
END

GO


