USE [DM_YG1]
GO

/****** Object:  StoredProcedure [dm_yg1_scm].[PROC_FACT_SCM_SUPPLY_SIMULATION_TB_INVEN_STATUS]    Script Date: 2025-07-25 오후 12:40:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






/****************************************************************************************************************
SP 명		: PROC_FACT_SCM_SUPPLY_SIMULATION_TB_INVEN_STATUS
SP 제목		: SCM 재고상태 마트 프로시저
최초작성자	: 최은수
최초작성일	: 2024.10.29
SP 실행 예	: EXEC PROC_FACT_SCM_SUPPLY_SIMULATION_TB_INVEN_STATUS 0
			  SELECT *	FROM dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_INVEN_STATUS 
SP 설명		: SCM 재고상태 테이블
				SELECT * FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_INVEN_STATUS	
			
			

변경이력		: 변경일/변경자/요청자/요청일/내용	
			 

	
******************************************************************************************************************/
CREATE PROCEDURE [dm_yg1_scm].[PROC_FACT_SCM_SUPPLY_SIMULATION_TB_INVEN_STATUS]

AS
BEGIN

	
	--공통변수
	DECLARE @SP_START_EXEC		DATETIME = GETDATE()	-- SP 실행시작시간
	DECLARE @INSERT_CNT	INT = 0			-- INSERT 건수
	DECLARE @UPDATE_CNT	INT = 0			-- UPDATE 건수
	DECLARE @DELETE_CNT	INT = 0			-- DELETE 건수
	DECLARE	@TABLE_NM	VARCHAR(50) = 'FACT_SCM_SUPPLY_SIMULATION_TB_INVEN_STATUS'	-- TARGET TABLE NAME
	DECLARE @ERR_MSG	VARCHAR(4000)
	DECLARE @ERR_NUM	NVARCHAR(20)
	DECLARE @ERR_LINE	INT

	
	
	DECLARE @COMPANY_CD	VARCHAR(12)	= '1000'	-- 회사코드 (SAP 필드명 : BUKRS) 

	BEGIN TRY

	DELETE FROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_INVEN_STATUS
	WHERE SAP_LOAD_DATE IN (SELECT ERSDA
	FROM DW_YG1.scm.TB_DW_DIM_ZDWT005_COOIS WITH(NOLOCK)
	WHERE ETL_DATE=(SELECT MAX(ETL_DATE) FROM  DW_YG1.scm.TB_DW_DIM_ZDWT005_COOIS)
	)
	SET @DELETE_CNT=@@ROWCOUNT


	INSERT INTO dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_INVEN_STATUS
	
	SELECT  
		A.CLIENT,
		A.SAP_LOAD_DATE,
		A.BOM_MATERIAL,
		ISNULL(A.ORDER_QTY,0) ORDER_QTY,
		ISNULL(C.MENGE,0) MENGE,
		ISNULL(B.ATP_QTY,0) ATP_QTY,
		CASE WHEN ISNULL(B.ATP_QTY,0)+ISNULL(C.MENGE,0)=0 THEN '무'
		WHEN ISNULL(B.ATP_QTY,0)-(ISNULL(A.ORDER_QTY,0) -ISNULL(C.MENGE,0) )>=0 THEN '충분'
		ELSE '부족' END [INVEN_STATUS],
		@SP_START_EXEC
	
	FROM(
	SELECT SAP_LOAD_DATE,CLIENT,
	BOM_MATERIAL,SUM(ISNULL(REQMTS_QTY,0)) ORDER_QTY
	fROM DM_YG1.dm_yg1_scm.FACT_SCM_SUPPLY_SIMULATION_TB_REPORT
	GROUP BY SAP_LOAD_DATE,CLIENT,
	BOM_MATERIAL
	) A
	LEFT OUTER JOIN(
	SELECT ERSDA,MANDT,MATNR,SUM(ISNULL(MENGE,0))  MENGE
	FROM DW_YG1.scm.TB_DW_FACT_ZDWT009_Z25MM001 WITH(NOLOCK)
	GROUP BY ERSDA,MANDT,MATNR ) C
	ON A.Client=C.MANDT AND A.BOM_MATERIAL=C.MATNR AND A.SAP_LOAD_DATE=C.ERSDA
	LEFT OUTER JOIN(
	SELECT ERSDA,MANDT,MATNR,SUM(ISNULL(LABST,0))  ATP_QTY
	FROM DW_YG1.scm.TB_DW_FACT_ZDWT007_Z25MM034 WITH(NOLOCK)
	WHERE LGORT<=2100
	GROUP BY ERSDA,MANDT,MATNR ) B
	ON A.SAP_LOAD_DATE=B.ERSDA AND A.BOM_MATERIAL=B.MATNR
	WHERE BOM_MATERIAL IS NOT NULL 
	AND A.SAP_LOAD_DATE IN (SELECT ERSDA
	FROM DW_YG1.scm.TB_DW_DIM_ZDWT005_COOIS WITH(NOLOCK)
	WHERE ETL_DATE=(SELECT MAX(ETL_DATE) FROM  DW_YG1.scm.TB_DW_DIM_ZDWT005_COOIS)
	)
	SET @INSERT_CNT=@@ROWCOUNT





		SET @INSERT_CNT	= @@ROWCOUNT

		INSERT INTO DW_YG1.DBO.TB_ETL_LOG
					(DB_NM			, SP_NM							, TABLE_NM		, START_DATE		, END_DATE		
					, INSERT_CNT	, DELETE_CNT	, UPDATE_CNT	, SUCCEESS_YN	, ERR_MSG			, ERR_NUM	, ERR_LINE)
			VALUES	(DB_NAME()		, OBJECT_NAME(@@PROCID)			, @TABLE_NM		, @SP_START_EXEC	, GETDATE()
					, @INSERT_CNT	, @DELETE_CNT	, @UPDATE_CNT	, 'Y'			, NULL				, NULL		, NULL)
			
	END TRY

	BEGIN CATCH
			
		SET @ERR_MSG	= ERROR_MESSAGE()
		SET @ERR_NUM	= ERROR_NUMBER()
		SET @ERR_LINE	= ERROR_LINE()

		PRINT	@ERR_MSG
		
		INSERT INTO DW_YG1.DBO.TB_ETL_LOG
				(DB_NM			, SP_NM							, TABLE_NM		, START_DATE		, END_DATE		
				, INSERT_CNT	, DELETE_CNT	, UPDATE_CNT	, SUCCEESS_YN	, ERR_MSG			, ERR_NUM		, ERR_LINE)
		VALUES	(DB_NAME()		, OBJECT_NAME(@@PROCID)			, @TABLE_NM		, @SP_START_EXEC	, GETDATE()
				, @INSERT_CNT	, @DELETE_CNT	, @UPDATE_CNT	, 'N'			, ERROR_MESSAGE()	, ERROR_NUMBER(), ERROR_LINE());
	END CATCH
END
GO


