COLUMN: CODE_NO int NULL
COLUMN: TEAM varchar(25) NOT NULL
COLUMN: T_CODE varchar(9) NOT NULL
COLUMN: VARIANT varchar(107) NOT NULL
COLUMN: TCODE_DESC varchar(46) NOT NULL
COLUMN: LOAD_PEROID varchar(13) NOT NULL
COLUMN: MIN_LOAD_DATE varchar(8) NOT NULL