CREATE   VIEW [scm].[VW_SCM_ZROUTING_CHANGE]
AS
SELECT 
MARC.DISPO,
MAPL.WERKS, MAPL.MATNR, MAPL.PLNNR, MAPL.PLNAL,
PLKO.KTEXT AS KOTXT, PLKO.DELKZ, PLKO.PLNME,
PLPO.VORNR, PLPO.STEUS, PLPO.BMSCH, PLPO.MEINH,
PLPO.VGW01, PLPO.VGE01, PLPO.VGW02, PLPO.VGE02,
PLPO.VGW03, PLPO.VGE03, PLPO.UMREN, PLPO.UMREZ,
PLPO.KTSCH, PLPO.LTXA1, 
PLPO.LOEKZ,
CRHD.ARBPL, CRHD.OBJID,
PLPO.INFNR, PLPO.LIFNR, 
MARA.LVORM AS LVORM_MARA, MARA.MSTAV,
MARC.LVORM AS LVORM_MARC, MARC.MMSTA,
MARA.MTART, MARA.MATKL as MATKL
FROM DW_YG1.dbo.TB_DW_DIM_MARC AS MARC
JOIN ODS_YG1.ods_scm.TB_ODS_ZROUTING_MAPL_CHANGE AS MAPL 
ON MARC.MATNR = MAPL.MATNR
AND MARC.WERKS = MAPL.WERKS
JOIN ODS_YG1.ods_scm.TB_ODS_ZROUTING_PLKO_CHANGE AS PLKO 
ON MAPL.PLNTY = PLKO.PLNTY
AND MAPL.PLNNR = PLKO.PLNNR
AND MAPL.PLNAL = PLKO.PLNAL
AND MAPL.ZAEHL = PLKO.ZAEHL
AND MAPL.WERKS = PLKO.WERKS
JOIN ODS_YG1.ods_scm.TB_ODS_ZROUTING_PLAS_CHANGE AS PLAS
ON PLKO.PLNTY = PLAS.PLNTY
AND PLKO.PLNNR = PLAS.PLNNR
AND PLKO.PLNAL = PLAS.PLNAL
JOIN ODS_YG1.ods_scm.TB_ODS_ZROUTING_PLPO_CHANGE AS PLPO 
ON PLAS.PLNTY = PLPO.PLNTY
AND PLAS.PLNNR = PLPO.PLNNR
AND PLAS.PLNKN = PLPO.PLNKN
AND PLAS.ZAEHL = PLPO.ZAEHL
AND PLKO.WERKS = PLPO.WERKS
JOIN ODS_YG1.ods_scm.TB_ODS_ZROUTING_CRHD_CHANGE AS CRHD 
ON PLPO.ARBID = CRHD.[OBJID]
AND PLPO.WERKS = CRHD.WERKS
JOIN DW_YG1.dbo.TB_DW_DIM_MARA AS MARA 
ON MARA.MATNR = MARC.MATNR
JOIN ODS_YG1.ods_scm.TB_ODS_ZROUTING_ZPPT075_CHANGE AS ZPPT075
ON PLKO.PLNNR=ZPPT075.PLNNR
AND PLKO.PLNAL=ZPPT075.PLNAL
AND PLKO.WERKS=ZPPT075.WERKS
AND PLPO.VORNR=ZPPT075.VORNR
AND CRHD.ARBPL=ZPPT075.ARBPL