CREATE VIEW SCM.VW_SCM_CAPALT_BASE
AS
WITH LT_BASE AS(
SELECT *
FROM(
SELECT 
A.MANDT,
A.ERSDA,A.AUFNR,A.APLZL,A.VORNR,A.KTSCH,
CASE WHEN B.VORNR='REL' THEN 0
WHEN B.VORNR='DLV' THEN 999
ELSE TRY_CONVERT(INT,B.VORNR,NULL) END as B_VORNR ,
GAMNG AS QTY,
VGW01 as SETUP_TIME,
VGW02 AS CYCLE_TIME,
GAMNG*VGW02+VGW01 AS [LT_MIN]
FROM SCM.TB_DW_FACT_ZDWT005_ROUTING_TB A
LEFT OUTER JOIN SCM.TB_DW_FACT_ZDWT006_Z25PP031 B
ON A.AUFNR=B.AUFNR AND A.ERSDA=B.ERSDA AND A.MANDT=B.MANDT
WHERE B.VORNR<>'CNF' OR B.VORNR<>'CLSD'
) A
)
SELECT *
FROM LT_BASE