COLUMN: DISPO nvarchar(18) NOT NULL
COLUMN: WERKS int NOT NULL
COLUMN: MATNR nvarchar(60) NOT NULL
COLUMN: PLNNR nvarchar(20) NOT NULL
COLUMN: PLNAL nvarchar(20) NOT NULL
COLUMN: KOTXT nvarchar(80) NULL
COLUMN: DELKZ nvarchar(2) NULL
COLUMN: PLNME nvarchar(6) NULL
COLUMN: VORNR nvarchar(8) NOT NULL
COLUMN: STEUS nvarchar(8) NULL
COLUMN: BMSCH decimal NULL
COLUMN: MEINH nvarchar(6) NULL
COLUMN: VGW01 decimal NULL
COLUMN: VGE01 nvarchar(6) NULL
COLUMN: VGW02 decimal NULL
COLUMN: VGE02 nvarchar(6) NULL
COLUMN: VGW03 decimal NULL
COLUMN: VGE03 nvarchar(6) NULL
COLUMN: UMREN decimal NULL
COLUMN: UMREZ decimal NULL
COLUMN: KTSCH nvarchar(60) NOT NULL
COLUMN: LTXA1 nvarchar(80) NULL
COLUMN: LOEKZ nvarchar(2) NULL
COLUMN: ARBPL nvarchar(60) NOT NULL
COLUMN: OBJID nvarchar(16) NOT NULL
COLUMN: INFNR nvarchar(20) NULL
COLUMN: LIFNR nvarchar(20) NOT NULL
COLUMN: LVORM_MARA nvarchar(6) NULL
COLUMN: MSTAV nvarchar(12) NULL
COLUMN: LVORM_MARC nvarchar(6) NULL
COLUMN: MMSTA nvarchar(12) NULL
COLUMN: MTART nvarchar(8) NULL
COLUMN: MATKL nvarchar(54) NULL
COLUMN: LOAD_DT datetime NULL