CREATE VIEW SCM.VW_TB_DW_DIM_MAKTL_GROUP
AS
SELECT 'EM-CSQ' MAKTL, '엔드밀' MAKTL_CAT_KOR UNION ALL
SELECT 'EM-CBR', '엔드밀' UNION ALL
SELECT 'EM-HSQ', '엔드밀' UNION ALL
SELECT 'DD-PP', '드릴' UNION ALL
SELECT 'EM-CRG', '엔드밀' UNION ALL
SELECT 'IX-BLK', 'IX밀' UNION ALL
SELECT 'IX', 'IX밀' UNION ALL
SELECT 'DD-GE', '드릴' UNION ALL
SELECT 'SD', '인서트' UNION ALL
SELECT 'EM-HRG', '엔드밀' UNION ALL
SELECT 'EM-SEMI', '엔드밀' UNION ALL
SELECT 'M-MAT', '엔드밀' UNION ALL
SELECT 'BR-BAR', '엔드밀' UNION ALL
SELECT 'CS', '리머, 카운터 등' UNION ALL
SELECT 'FR-REGIND', '재연마' UNION ALL
SELECT 'SD-BLK', '인서트' UNION ALL
SELECT 'IO-BLK', '인서트' UNION ALL
SELECT 'TA-CAR', '탭' UNION ALL
SELECT 'IO', '인서트' UNION ALL
SELECT 'EM-HBR', '엔드밀' UNION ALL
SELECT 'RM', '리머, 카운터 등' UNION ALL
SELECT 'ID-BLK', '인서트' UNION ALL
SELECT 'ID', '인서트' UNION ALL
SELECT 'HD', '홀더' UNION ALL
SELECT 'EM-HCB', '엔드밀' UNION ALL
SELECT 'DD-MQ', '드릴' UNION ALL
SELECT 'TM', '쓰레드밀' UNION ALL
SELECT 'DR-CT', '리머, 카운터 등' UNION ALL
SELECT 'DD-HF', '드릴' UNION ALL
SELECT 'MH', '인서트' UNION ALL
SELECT 'FR-SUBCN', '인서트' UNION ALL
SELECT 'MH-BLK', '인서트' UNION ALL
SELECT 'DR-STP', '리머, 카운터 등' UNION ALL
SELECT 'TA-BLK', '탭' UNION ALL
SELECT 'EM-HCR', '엔드밀' UNION ALL
SELECT 'DR-HPD', '드릴' UNION ALL
SELECT 'DD-BLK', '리머, 카운터 등' UNION ALL
SELECT 'EM-BLK', '엔드밀' UNION ALL
SELECT 'DR-MT1', '리머, 카운터 등' UNION ALL
SELECT 'RT', '리머, 카운터 등' UNION ALL
SELECT 'DR-SS13', '리머, 카운터 등' UNION ALL
SELECT 'RB', '로타리버' UNION ALL
SELECT 'DR-SSC', '리머, 카운터 등' UNION ALL
SELECT 'EM-CBN', '엔드밀' UNION ALL
SELECT 'DR-NC', '리머, 카운터 등' UNION ALL
SELECT 'EM-PCD', '리머, 카운터 등' UNION ALL
SELECT 'DR-TS30', '리머, 카운터 등' UNION ALL
SELECT 'DR-NCR', '리머, 카운터 등' UNION ALL
SELECT 'DR-PCD', '리머, 카운터 등' UNION ALL
SELECT 'DR-CTR', '리머, 카운터 등' 