COLUMN: MANDT int NOT NULL
COLUMN: ERSDA nvarchar(16) NOT NULL
COLUMN: AUFNR bigint NOT NULL
COLUMN: VORNR int NOT NULL
COLUMN: KTSCH nvarchar(14) NULL
COLUMN: LTXA1 nvarchar(80) NULL
COLUMN: AUTYP nvarchar(4) NULL
COLUMN: GAMNG decimal NULL
COLUMN: IAMNG decimal NULL
COLUMN: IASMG decimal NULL
COLUMN: BMEINS nvarchar(6) NULL
COLUMN: GSTRI int NULL
COLUMN: GLTRI int NULL
COLUMN: ZTNOR decimal NULL
COLUMN: ZEITN nvarchar(6) NULL
COLUMN: WARTZ float NULL
COLUMN: WRTZE nvarchar(6) NULL
COLUMN: BMSCH decimal NULL
COLUMN: VGW01 decimal NULL
COLUMN: VGE01 nvarchar(6) NULL
COLUMN: VGW02 decimal NULL
COLUMN: VGE02 nvarchar(6) NULL
COLUMN: VGW03 decimal NULL
COLUMN: VGE03 nvarchar(6) NULL
COLUMN: AUART nvarchar(8) NULL
COLUMN: IGMNG decimal NULL
COLUMN: ETL_DATE datetime NOT NULL
COLUMN: AUFPL int NULL
COLUMN: APLZL int NULL
COLUMN: ARBID int NULL