CREATE VIEW [scm].[VW_PSI_RATIO_VIEW] AS 
WITH MAIN AS(
SELECT 
CASE WHEN VTWEG=10 THEN '국내'
WHEN VTWEG=20 THEN '해외'
ELSE NULL END 
as DOMAIN,
MANDT,
ERSDA,
MATNR,
KWMENG
FROM Scm.TB_DW_FACT_ZDWT010_Z25SD003
WHERE VTWEG=10 OR VTWEG=20
),DOMAINSUM AS(
SELECT DOMAIN,MANDT,ERSDA,MATNR, SUM(KWMENG) as S
FROM MAIN
GROUP BY DOMAIN ,MANDT,ERSDA,MATNR
),MATSUM AS (
SELECT MANDT,ERSDA,MATNR, SUM(KWMENG) as S
FROM MAIN
GROUP BY  MANDT,ERSDA,MATNR
)
SELECT 
A.MANDT,
A.ERSDA,
A.MATNR,
A.DOMAIN,
A.S/B.S AS RATIO
FROM DOMAINSUM A
LEFT OUTER JOIN MATSUM B
ON A.MANDT=B.MANDT AND A.ERSDA=B.ERSDA
AND A.MATNR=B.MATNR