CREATE VIEW [scm].[VW_FACT_SCM_SUPPLY_SIMULATION_TB_VISUAL_DF]
AS
SELECT 
CLIENT,
SAP_LOAD_DATE,
PO [작번],
MATERIAL as [Material],
MATKL [MRP Ctrlr],
CASE WHEN REQMTS_QTY<=INV_QTY THEN '충분' 
WHEN INV_QTY=0 THEN '무'
ELSE '부족' END as INVEN_STATUS
FROM DW_YG1.scm.TB_DW_FACT_SCM_SUPPLY_SIMULATION_TB