COLUMN: MANDT int NOT NULL
COLUMN: ERSDA nvarchar(16) NOT NULL
COLUMN: RSNUM nvarchar(20) NOT NULL
COLUMN: RSPOS nvarchar(8) NOT NULL
COLUMN: BDTER int NULL
COLUMN: WERKS int NULL
COLUMN: LGORT int NULL
COLUMN: UMLGO int NULL
COLUMN: MATNR nvarchar(60) NULL
COLUMN: CHARG nvarchar(20) NULL
COLUMN: MENGE numeric NULL
COLUMN: WAMNG numeric NULL
COLUMN: AUFNR bigint NULL
COLUMN: POSNR nvarchar(20) NOT NULL
COLUMN: MBLNR nvarchar(20) NULL
COLUMN: ZEILE nvarchar(10) NULL
COLUMN: MEINS nvarchar(6) NULL
COLUMN: MAKTX nvarchar(100) NULL
COLUMN: MATKL nvarchar(20) NULL
COLUMN: BAUGR nvarchar(36) NULL
COLUMN: BDMNG numeric NULL
COLUMN: FLG nvarchar(2) NULL
COLUMN: NTGEW numeric NULL
COLUMN: GEWEI nvarchar(6) NULL
COLUMN: BUKRS nvarchar(8) NULL
COLUMN: NAME1 nvarchar(60) NULL
COLUMN: ETL_DATE date NULL