CREATE VIEW scm.VW_TB_DW_FACT_ZDWT005_ROUTING_TB_APLZL_STARTWITH_0
AS
SELECT A.[MANDT]
,A.[ERSDA]
,A.[AUFNR]
,[VORNR]
,[KTSCH]
,[LTXA1]
,[AUTYP]
,[GAMNG]
,[IAMNG]
,[IASMG]
,[BMEINS]
,[GSTRI]
,[GLTRI]
,[ZTNOR]
,[ZEITN]
,[WARTZ]
,[WRTZE]
,[BMSCH]
,[VGW01]
,[VGE01]
,[VGW02]
,[VGE02]
,[VGW03]
,[VGE03]
,[AUART]
,[IGMNG]
,[ETL_DATE]
,[AUFPL]
,[APLZL]-b.MINAPLZL+1 as APLZL
,[ARBID]
FROM DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB A
JOIN(
SELECT
MANDT,ERSDA,AUFNR,MIN(APLZL) MINAPLZL
FROM DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB 
GROUP BY  MANDT,ERSDA,AUFNR
) B
ON A.AUFNR=B.AUFNR AND A.ERSDA=B.ERSDA AND A.MANDT=B.MANDT