/*
인벤토리정보 조달생산가시화용
*/
create VIEW [scm].[VW_TB_DW_FACT_ZDWT007_Z25MM034_PSI]
AS
SELECT 
A.MANDT AS CLIENT,
A.MATNR MATERIAL,
B.MAKTG [DESCRIPTION],
NULL SPEC,
WERKS AS PLANT,
LGORT AS SLOC,
ATP_QTY,
LABST AS UNRESTRICTED_STOCK,
INSME AS QI_STOCK,
SPEME AS BLOCED_STOCK,
LIFNR AS MAKER,
NAME1 AS MAKER_NAME,
SPART AS DIVISION,
NULL AS PRICE,
NULL AS TOOL_NO,
MTART AS MATERIAL_TYPE,
NULL AS RAW_MATERIAL,
CLASS AS CLASS,
CHARG AS BATCH,
NULL AS COATING_TYPE,
NULL AS ORDER_PRICE,
MEINS AS BARCH1,
GRDP_002 AS GRDP2,
PRDHA AS PRODHIERARCHY_DES,
GRDP_PLC,
WZEIT AS LEAD_TIME,
NULL AS PACKING_STD,
EISBE AS Safety_Stock,
MAABC AS ABC,
NULL AS RAWMTLWEIGHT,
NULL AS RAWMTLWEIUNIT,
NULL AS BATCH_DESC,
A.ERSDA AS SIMULATION_DATE
FROM SCM.TB_DW_FACT_ZDWT007_Z25MM034 A
JOIN DW_YG1.DBO.TB_DW_DIM_MAKT B
ON A.MANDT=B.MANDT AND A.MATNR=B.MATNR
WHERE [LGORT]>2100