/****************************************************************************************************************
SP 명  : PROC_TB_DW_FACT_ZDWT005_ROUTING_TB
SP Owner    : scm
SP 제목  : INPUT 
최초작성자 : 최은수
최초작성일 : 2024.09.11
SP 실행 예 : EXEC scm.PROC_TB_DW_FACT_ZDWT005_ROUTING_TB
SP 설명  : PLAN 입력
변경이력  : 변경일/변경자/요청자/요청일/내용 
******************************************************************************************************************/
CREATE PROCEDURE [scm].[PROC_TB_DW_FACT_ZDWT005_ROUTING_TB]
 @CUR_DATE DATE
AS
BEGIN
DECLARE 
  @INSERT_CNT INT = 0,  -- INSERT 건수
  @UPDATE_CNT INT = 0,  -- UPDATE 건수
  @DELETE_CNT INT = 0,  -- DELETE 건수
  @TABLE_NM VARCHAR(50) = 'TB_DW_FACT_ZDWT005_ROUTING_TB',   -- TARGET TABLE NAME
  @SP_START_EXEC DATETIME = GETDATE()             -- SP 실행시작시간
 BEGIN TRY
  DELETE FROM scm.TB_DW_FACT_ZDWT005_ROUTING_TB
  WHERE ERSDA IN (SELECT DISTINCT ERSDA FROM ODS_YG1.ODS_SCM.TB_ODS_ZDWT005_COOIS_CHANGE )
  SET @DELETE_CNT=@@ROWCOUNT
  INSERT INTO DW_YG1.scm.TB_DW_FACT_ZDWT005_ROUTING_TB
  SELECT
  A.MANDT,
  A.ERSDA,
  A.AUFNR,
  V.VORNR  ,
  V.KTSCH  ,
  V.LTXA1  ,
  U.AUTYP  ,
  A.GAMNG  ,
  A.IAMNG  ,
  A.IASMG  ,
  BMEINS  ,
  A.GSTRI  ,
  A.GLTRI  ,
  ZTNOR  ,
  ZEITN  ,
  WARTZ  ,
  WRTZE  ,
  F.BMSCH  ,
  F.VGW01 ,
  F.VGE01,
  F.VGW02 ,
  F.VGE02,
  F.VGW03,
  F.VGE03,
  A.AUART ,
  A.IGMNG ,
  @SP_START_EXEC as ETL_DATE,
  V.AUFPL,
  V.APLZL,
  V.ARBID
  FROM ODS_YG1.ODS_SCM.TB_ODS_ZDWT005_COOIS_CHANGE A
  JOIN ODS_YG1.[ods_scm].[TB_ODS_SCM_AFKO_CHANGE] K 
  ON A.AUFNR = K.AUFNR AND A.MANDT=K.MANDT    
  JOIN ODS_YG1.[ods_scm].[TB_ODS_SCM_AFVC_CHANGE] V 
  ON K.AUFPL = V.AUFPL AND K.MANDT=V.MANDT       -- 작업 정보를 연결
  JOIN ODS_YG1.[ods_scm].TB_ODS_SCM_AFVV_CHANGE F
  ON V.AUFPL=F.AUFPL AND V.MANDT=F.MANDT AND V.APLZL=F.APLZL
  JOIN ODS_YG1.[ods_scm].[TB_ODS_SCM_AUFK_CHANGE] U
  ON A.AUFNR=U.AUFNR AND A.MANDT=U.MANDT
  SET @INSERT_CNT=@@ROWCOUNT
  
  INSERT INTO DW_YG1.DBO.TB_ETL_LOG
     (DB_NM   , SP_NM       , TABLE_NM  , START_DATE  , END_DATE  
     , INSERT_CNT , DELETE_CNT , UPDATE_CNT , SUCCEESS_YN , ERR_MSG   , ERR_NUM , ERR_LINE)
   VALUES (DB_NAME()  , OBJECT_NAME(@@PROCID)   , @TABLE_NM  , @SP_START_EXEC , GETDATE()
     , @INSERT_CNT , @DELETE_CNT , @UPDATE_CNT , 'Y'   , NULL    , NULL  , NULL)
 END TRY
 BEGIN CATCH
  INSERT INTO DW_YG1.DBO.TB_ETL_LOG
     (DB_NM   , SP_NM       , TABLE_NM  , START_DATE  , END_DATE  
     , INSERT_CNT , DELETE_CNT , UPDATE_CNT , SUCCEESS_YN , ERR_MSG   , ERR_NUM  , ERR_LINE)
   VALUES (DB_NAME()  , OBJECT_NAME(@@PROCID)   , @TABLE_NM  , @SP_START_EXEC , GETDATE()
     , @INSERT_CNT , @DELETE_CNT , @UPDATE_CNT , 'N'   , ERROR_MESSAGE() , ERROR_NUMBER(), ERROR_LINE())
  
  RETURN
 END CATCH
END