CREATE   VIEW  [scm].[VW_TB_DW_FACT_ZDWT010_Z25SD003_SUPPLY_SO]
AS
SELECT 
A.[MANDT] CLIENT
,[VKORG] [Sales Organization]
,VTWEG [Distribution Chan.]
,B.VBELN [Sales Doc No]
,POSNR [Item No]
,MATNR [Material]
,FERTH [Uncoat]
,KWMENG [Order Qty]
,MEINS UNIT
,P_QTY [Pending Qty]
,RFMNG_1 [Deliv Qty]
,BSTDK_E  [Customer Delivery Date]
,B.AUDAT AS [Doc. Date]
,[ERSDA] SIMULATION_DATE
FROM SCM.TB_DW_FACT_ZDWT010_Z25SD003 A
JOIN ODS_YG1.ods_scm.TB_ODS_ZDWT010_Z25SD003_VBAK B
ON A.MANDT=B.MANDT AND A.VBELN=B.VBELN