COLUMN: CLIENT int NOT NULL
COLUMN: SAP_LOAD_DATE nvarchar(8000) NULL
COLUMN: ERSDA date NULL
COLUMN: MATNR varchar(30) NOT NULL
COLUMN: REGION varchar(4) NULL
COLUMN: CurrentINVEN numeric NULL
COLUMN: 0WeekINVEN numeric NULL
COLUMN: 1WeekINVEN numeric NULL
COLUMN: 2WeekINVEN numeric NULL
COLUMN: 3WeekINVEN numeric NULL
COLUMN: 4WeekINVEN numeric NULL
COLUMN: 5WeekINVEN numeric NULL
COLUMN: 6WeekINVEN numeric NULL
COLUMN: 7WeekINVEN numeric NULL
COLUMN: 8WeekINVEN numeric NULL
COLUMN: 9WeekINVEN numeric NULL
COLUMN: 10WeekINVEN numeric NULL
COLUMN: 11WeekINVEN numeric NULL
COLUMN: 12WeekINVEN numeric NULL
COLUMN: 0WeekPROD numeric NULL
COLUMN: 1WeekPROD numeric NULL
COLUMN: 2WeekPROD numeric NULL
COLUMN: 3WeekPROD numeric NULL
COLUMN: 4WeekPROD numeric NULL
COLUMN: 5WeekPROD numeric NULL
COLUMN: 6WeekPROD numeric NULL
COLUMN: 7WeekPROD numeric NULL
COLUMN: 8WeekPROD numeric NULL
COLUMN: 9WeekPROD numeric NULL
COLUMN: 10WeekPROD numeric NULL
COLUMN: 11WeekPROD numeric NULL
COLUMN: 12WeekPROD numeric NULL
COLUMN: 0WeekSales numeric NOT NULL
COLUMN: 1WeekSales numeric NOT NULL
COLUMN: 2WeekSales numeric NOT NULL
COLUMN: 3WeekSales numeric NOT NULL
COLUMN: 4WeekSales numeric NOT NULL
COLUMN: 5WeekSales numeric NOT NULL
COLUMN: 6WeekSales numeric NOT NULL
COLUMN: 7WeekSales numeric NOT NULL
COLUMN: 8WeekSales numeric NOT NULL
COLUMN: 9WeekSales numeric NOT NULL
COLUMN: 10WeekSales numeric NOT NULL
COLUMN: 11WeekSales numeric NOT NULL
COLUMN: 12WeekSales numeric NOT NULL
COLUMN: PENDING_PROD numeric NOT NULL
COLUMN: PENDING_SALES numeric NOT NULL
COLUMN: ETL_DATE datetime NOT NULL
COLUMN: PRODH varchar(10) NULL
COLUMN: VTEXT nvarchar(200) NULL