COLUMN: CLIENT int NOT NULL
COLUMN: SAP_LOAD_DATE int NOT NULL
COLUMN: WORK_CENTER varchar(6) NOT NULL
COLUMN: WORK_CENTER_NAME varchar(29) NOT NULL
COLUMN: APPLYED_MACHINE_NUMBER numeric NOT NULL
COLUMN: CORRECTION_MACHINE_NUMBER numeric NOT NULL
COLUMN: MACHINE_NUMBER int NOT NULL
COLUMN: CAPABALANCE_RATE numeric NOT NULL
COLUMN: WEEKLY_CAPACITY int NULL
COLUMN: ETL_TIME date NULL