COLUMN: CLIENT int NOT NULL
COLUMN: SAP_LOAD_DATE int NOT NULL
COLUMN: BOM_MATERIAL varchar(30) NOT NULL
COLUMN: ORDER_QTY numeric NULL
COLUMN: PRE_PROC_QTY numeric NULL
COLUMN: INVEN_QTY numeric NULL
COLUMN: INVEN_STATUS nvarchar(20) NULL
COLUMN: ETL_DATE date NULL