COLUMN: CLIENT int NOT NULL
COLUMN: SAP_LOAD_DATE varchar(8) NOT NULL
COLUMN: PO bigint NOT NULL
COLUMN: REMAINED_LT int NULL
COLUMN: WORK_COUNT int NULL
COLUMN: WORK_CENTER_TEXT nvarchar(14) NULL
COLUMN: WORK_STATUS int NOT NULL
COLUMN: WORK_DATE nvarchar(20) NULL
COLUMN: STATUS varchar(6) NULL
COLUMN: AUFPL int NULL
COLUMN: APLZL int NULL
COLUMN: WORK_PROCESS nvarchar(20) NULL
COLUMN: ETL_DATE datetime NOT NULL