COLUMN: CLIENT int NOT NULL
COLUMN: SAP_LOAD_DATE int NOT NULL
COLUMN: WORK_CENTER varchar(10) NOT NULL
COLUMN: MFG_GROUP varchar(20) NOT NULL
COLUMN: OPERATION_HOUR numeric NULL
COLUMN: WORKCENTER_NAME nvarchar(100) NOT NULL
COLUMN: OPERATION_QTY int NULL
COLUMN: WORK_YEAR int NOT NULL
COLUMN: WORK_WEEK int NOT NULL
COLUMN: IS_GRAPH int NULL
COLUMN: ETL_TIME datetime NOT NULL