COLUMN: MANDT int NOT NULL
COLUMN: ERSDA nvarchar(16) NOT NULL
COLUMN: MATNR nvarchar(60) NOT NULL
COLUMN: WERKS int NOT NULL
COLUMN: LGORT int NOT NULL
COLUMN: CHARG nvarchar(20) NOT NULL
COLUMN: MAKTX nvarchar(100) NULL
COLUMN: GROES nvarchar(64) NULL
COLUMN: ATP_QTY numeric NULL
COLUMN: LABST numeric NULL
COLUMN: INSME numeric NULL
COLUMN: SPEME numeric NULL
COLUMN: SPART nvarchar(4) NULL
COLUMN: MTART nvarchar(10) NULL
COLUMN: MEINS nvarchar(6) NULL
COLUMN: LIFNR nvarchar(20) NULL
COLUMN: NAME1 nvarchar(60) NULL
COLUMN: REMARK nvarchar(100) NULL
COLUMN: CLASS nvarchar(36) NULL
COLUMN: ATWRT nvarchar(60) NULL
COLUMN: ATWRT1 nvarchar(60) NULL
COLUMN: ATWRT2 nvarchar(60) NULL
COLUMN: ATWRT3 nvarchar(60) NULL
COLUMN: PRDHA nvarchar(60) NULL
COLUMN: VTEXT nvarchar(40) NULL
COLUMN: GRDP_PLC nvarchar(6) NULL
COLUMN: GRDP_002 nvarchar(30) NULL
COLUMN: NORMT nvarchar(40) NULL
COLUMN: WZEIT numeric NULL
COLUMN: EISBE numeric NULL
COLUMN: LVORM nvarchar(10) NULL
COLUMN: MAABC nvarchar(10) NULL
COLUMN: STPRS numeric NULL
COLUMN: PEINH numeric NULL
COLUMN: WAERS nvarchar(10) NULL
COLUMN: NTGEW numeric NULL
COLUMN: GEWEI nvarchar(6) NULL
COLUMN: B_DES nvarchar(MAX) NULL
COLUMN: ETL_DATE date NULL