COLUMN: MATNR varchar(30) NULL
COLUMN: ROUTING varchar(20) NULL
COLUMN: MFG varchar(30) NULL
COLUMN: SEMI_P nvarchar(MAX) NULL
COLUMN: MATNR_GROUP nvarchar(MAX) NULL
COLUMN: MATERIAL_DESC nvarchar(MAX) NULL
COLUMN: GROES nvarchar(MAX) NULL
COLUMN: MATERIAL_TYPE nvarchar(MAX) NULL