COLUMN: MANDT int NOT NULL
COLUMN: ERSDA int NOT NULL
COLUMN: MATNR varchar(30) NOT NULL
COLUMN: WERKS int NOT NULL
COLUMN: LGORT int NOT NULL
COLUMN: CHARG varchar(10) NOT NULL
COLUMN: MAKTX nvarchar(80) NULL
COLUMN: GROES nvarchar(64) NULL
COLUMN: ATP_QTY decimal NULL
COLUMN: LABST decimal NULL
COLUMN: INSME decimal NULL
COLUMN: SPEME decimal NULL
COLUMN: SPART nvarchar(4) NULL
COLUMN: MTART nvarchar(8) NULL
COLUMN: MEINS nvarchar(6) NULL
COLUMN: LIFNR nvarchar(20) NULL
COLUMN: NAME1 nvarchar(70) NULL
COLUMN: REMARK nvarchar(100) NULL
COLUMN: CLASS nvarchar(36) NULL
COLUMN: ATWRT nvarchar(60) NULL
COLUMN: ATWRT1 nvarchar(60) NULL
COLUMN: ATWRT2 nvarchar(60) NULL
COLUMN: ATWRT3 nvarchar(60) NULL
COLUMN: PRDHA nvarchar(36) NULL
COLUMN: VTEXT nvarchar(80) NULL
COLUMN: GRDP_PLC nvarchar(6) NULL
COLUMN: GRDP_002 nvarchar(30) NULL
COLUMN: NORMT nvarchar(36) NULL
COLUMN: WZEIT decimal NULL
COLUMN: EISBE decimal NULL
COLUMN: LVORM nvarchar(2) NULL
COLUMN: MAABC nvarchar(2) NULL
COLUMN: STPRS decimal NULL
COLUMN: PEINH decimal NULL
COLUMN: WAERS nvarchar(10) NULL
COLUMN: NTGEW decimal NULL
COLUMN: GEWEI nvarchar(6) NULL
COLUMN: B_DES nvarchar(510) NULL
COLUMN: LOAD_DT datetime NOT NULL