COLUMN: MANDT int NOT NULL
COLUMN: ERSDA nvarchar(16) NOT NULL
COLUMN: RSNUM nvarchar(20) NOT NULL
COLUMN: RSPOS nvarchar(8) NOT NULL
COLUMN: RSDAT int NULL
COLUMN: SBTER int NULL
COLUMN: BDTER int NULL
COLUMN: MATNR nvarchar(60) NULL
COLUMN: MAKTX nvarchar(100) NULL
COLUMN: FERTH nvarchar(36) NULL
COLUMN: LGORT int NULL
COLUMN: BDMNG numeric NULL
COLUMN: MEINS nvarchar(6) NULL
COLUMN: GRDP_PLC nvarchar(6) NULL
COLUMN: GRDP_ABC nvarchar(4) NULL
COLUMN: UMLGO int NULL
COLUMN: WERKS int NULL
COLUMN: DOSTK numeric NULL
COLUMN: EXCST numeric NULL
COLUMN: SAFS1 numeric NULL
COLUMN: SAFS2 numeric NULL
COLUMN: AVAS1 numeric NULL
COLUMN: AVAS2 numeric NULL
COLUMN: ZFIX nvarchar(10) NULL
COLUMN: ETL_DATE date NULL