COLUMN: WERKS varchar(4) NOT NULL
COLUMN: LGORT int NOT NULL
COLUMN: SAP_Descriptinon varchar(16) NOT NULL
COLUMN: DESC_KOR varchar(23) NOT NULL
COLUMN: LOC varchar(4) NOT NULL
COLUMN: DESC_TEXT varchar(16) NOT NULL
COLUMN: REGION varchar(4) NULL