COLUMN: MANDT int NOT NULL
COLUMN: ERSDA nvarchar(16) NOT NULL
COLUMN: AEDAT int NOT NULL
COLUMN: LIFNR nvarchar(20) NOT NULL
COLUMN: WAERS nvarchar(10) NOT NULL
COLUMN: WKURS numeric NOT NULL
COLUMN: EBELN nvarchar(20) NOT NULL
COLUMN: EBELP nvarchar(10) NOT NULL
COLUMN: MATNR nvarchar(60) NULL
COLUMN: NETPR numeric NULL
COLUMN: MENGE numeric NULL
COLUMN: ELIKZ nvarchar(2) NULL
COLUMN: AFNAM nvarchar(24) NULL
COLUMN: EINDT int NULL
COLUMN: CHARG nvarchar(20) NULL
COLUMN: KNTTP nvarchar(2) NULL
COLUMN: PSTYP nvarchar(2) NULL
COLUMN: MTART nvarchar(10) NULL
COLUMN: PRDHA nvarchar(60) NULL
COLUMN: VBELN2 nvarchar(20) NULL
COLUMN: VBELP2 nvarchar(20) NULL
COLUMN: WERKS int NULL
COLUMN: MEINS nvarchar(6) NULL
COLUMN: LGORT int NULL
COLUMN: LABNR nvarchar(40) NULL
COLUMN: ERNAM nvarchar(24) NULL
COLUMN: EKGRP nvarchar(6) NULL
COLUMN: BEDAT int NULL
COLUMN: GROES nvarchar(64) NULL
COLUMN: PEINH numeric NULL
COLUMN: BPRME nvarchar(10) NULL
COLUMN: UMREZ numeric NULL
COLUMN: LMEIN nvarchar(10) NULL
COLUMN: BPUMN numeric NULL
COLUMN: BPUMZ numeric NULL
COLUMN: UMREN numeric NULL
COLUMN: MAKTX nvarchar(100) NULL
COLUMN: NAME1 nvarchar(60) NULL
COLUMN: VTEXT nvarchar(40) NULL
COLUMN: GR_QTY numeric NULL
COLUMN: STOCK numeric NULL
COLUMN: PO_BAL numeric NULL
COLUMN: PE_QTY numeric NULL
COLUMN: ETL_DATE date NULL