COLUMN: MANDT int NOT NULL
COLUMN: ERSDA nvarchar(16) NOT NULL
COLUMN: VKORG nvarchar(10) NOT NULL
COLUMN: VTWEG nvarchar(10) NOT NULL
COLUMN: VBELN nvarchar(20) NOT NULL
COLUMN: POSNR nvarchar(20) NOT NULL
COLUMN: MATNR nvarchar(60) NULL
COLUMN: FERTH nvarchar(36) NULL
COLUMN: KWMENG numeric NULL
COLUMN: MEINS nvarchar(6) NULL
COLUMN: P_QTY numeric NULL
COLUMN: RFMNG_1 numeric NULL
COLUMN: BSTDK_E int NULL
COLUMN: ETL_DATE date NULL
COLUMN: AUDAT int NULL